const imgBonhoeffer = [
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927518/calidad_images/bonhoeffer/Selecci%C3%B3n_002_drk3s0.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927517/calidad_images/bonhoeffer/Selecci%C3%B3n_003_qxb09d.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927517/calidad_images/bonhoeffer/Selecci%C3%B3n_001_nmvfnw.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927517/calidad_images/bonhoeffer/Selecci%C3%B3n_004_vt4pz8.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927517/calidad_images/bonhoeffer/Selecci%C3%B3n_005_gbo08i.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927517/calidad_images/bonhoeffer/Selecci%C3%B3n_006_lae5en.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927517/calidad_images/bonhoeffer/Selecci%C3%B3n_007_fs2utd.png'
];

const imgCifarelli = [
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927529/calidad_images/cifarelli/Selecci%C3%B3n_001_l6zixf.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927528/calidad_images/cifarelli/Selecci%C3%B3n_003_viwwwm.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927528/calidad_images/cifarelli/Selecci%C3%B3n_002_gt3nmi.png'
];

const imgDucati = [
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927540/calidad_images/ducati/Selecci%C3%B3n_001_dymlxv.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927540/calidad_images/ducati/Selecci%C3%B3n_002_gpkzhi.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927540/calidad_images/ducati/Selecci%C3%B3n_003_d0ykaf.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927540/calidad_images/ducati/Selecci%C3%B3n_004_gkm6az.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927539/calidad_images/ducati/Selecci%C3%B3n_005_bsrr3c.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927539/calidad_images/ducati/Selecci%C3%B3n_006_laqort.png'
];

const imgHonda = [
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927555/calidad_images/honda/Selecci%C3%B3n_001_eoftxj.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927555/calidad_images/honda/Selecci%C3%B3n_002_g3cya4.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927554/calidad_images/honda/Selecci%C3%B3n_003_d9hecg.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927554/calidad_images/honda/Selecci%C3%B3n_004_jy1ur8.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927553/calidad_images/honda/Selecci%C3%B3n_005_prtcgo.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927553/calidad_images/honda/Selecci%C3%B3n_006_dknzj0.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927553/calidad_images/honda/Selecci%C3%B3n_007_wab6yq.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927553/calidad_images/honda/Selecci%C3%B3n_008_f5c6e9.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927553/calidad_images/honda/Selecci%C3%B3n_009_zaeoro.png'
];

const imgRato = [
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927567/calidad_images/rato/Selecci%C3%B3n_001_qemijf.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927566/calidad_images/rato/Selecci%C3%B3n_002_suifrh.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927566/calidad_images/rato/Selecci%C3%B3n_003_zkpkac.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927565/calidad_images/rato/Selecci%C3%B3n_004_nlbrd6.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927565/calidad_images/rato/Selecci%C3%B3n_006_fo8f0o.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927565/calidad_images/rato/Selecci%C3%B3n_007_smyhnw.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927565/calidad_images/rato/Selecci%C3%B3n_008_mhphdh.png',
  'https://res.cloudinary.com/del5cxt4n/image/upload/v1751927565/calidad_images/rato/Selecci%C3%B3n_009_btjhtp.png'
];

export const products = [
  {
    title: 'Atomizador de Mochila Cifarelli L3EVO18',
    brand: 'Cifarelli',
    imageUrl: imgCifarelli[Math.round(Math.random() * (imgCifarelli.length - 1))],
    model: 'L3EVO18',
    category: 'Atomizador',
    specs: {
      applications: [
        'Control de plagas en hortalizas y frutales',
        'Control de vectores y demás aplicaciones de Sanidad Pública',
      ],
      engineType:
        'CIFARELLI C7 monocilíndrico de 2 tiempos refrigerado por aire',
      displacementCc: 77,
      bore: 52,
      stroke: 36,
      maxPowerHp: 5,
      powerKw: 3.6,
      carburetor: 'Carburador',
      ignitionSystem: 'Encendido electrónico',
      sparkPlug: 'CHAMPION RCJ6Y',
      fuelTankCapacityL: 1.9,
      fuelType: 'Mezcla de gasolina y aceite para 2 tiempos',
      liquidTankCapacityL: 18,
      liquidFlowRateLmin: 3.6,
      dropletSize: 'Ø 120 µm',
      maxHorizontalRangeM: 17,
      maxVerticalRangeM: 15,
      airVolumeM3h: 1200,
      airSpeedMps: 125,
      acceleration: '450 Km/h / 280 MPH',
      handleType: 'Empuñadura con gatillo de aceleración',
      noiseLevelLpfaDb: 98.7,
      noiseLevelLwaDb: 113.6,
      vibrationLevelMss: 3.5,
      weightWithoutTubeKg: 10.62,
      weightWithTubeKg: 11.36,
      packagingDimensionsCm: '49 x 74 x 38',
      accessories: [
        'Llave sacabujía con destornillador - cabeza hexagonal',
        'Abrazaderas Ø 67',
        'Botella para preparación mezcla de combustible',
        'Tobera (boquilla pulverizadora)',
        'Boca difusora',
        'Kit de rejillas (cod.: 0G34100)',
      ],
      manufacturer: 'CIFARELLI S.P.A. MADE IN ITALY',
      membraneRuixing: 'Graduada: 18 L / Máxima: 20 L',
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Soplador de Mochila Cifarelli BL 1200',
    brand: 'Cifarelli',
    imageUrl: imgCifarelli[Math.round(Math.random() * (imgCifarelli.length - 1))],
    model: 'BL 1200',
    category: 'Soplador',
    specs: {
      applications: [
        'Limpieza de grandes áreas eliminando hojas, hierba u otro material',
        'Recolección de aceitunas y frutos con cáscara como castañas o avellanas',
        'En apicultura, se emplea para alejar a las abejas de las colmenas durante la extracción de miel',
      ],
      engineType:
        'CIFARELLI C7 monocilíndrico de 2 tiempos refrigerado por aire',
      displacementCc: 77,
      bore: 52,
      stroke: 36,
      maxPowerHp: 5,
      powerKw: 3.6,
      carburetor: 'WALBRO de membrana con cápsula',
      ignitionSystem: 'Encendido electrónico',
      sparkPlug: 'CHAMPION RCJ6Y',
      fuelTankCapacityL: 2.3,
      fuelType: 'Mezcla de gasolina y aceite para 2 tiempos',
      tubeType: 'Tubo telescópico',
      diffuserType: 'Difusores',
      airVolumeWithoutBlowerM3h: 1620,
      airVolumeWithBlowerM3h: 1092,
      airSpeedMps: 82.3,
      acceleration: '296 Km/h / 184 MPH (con dispositivo de soplado)',
      handleType: 'Empuñadura con gatillo de aceleración',
      noiseLevelLpfaMaxDb: 78,
      noiseLevelLpfaMinDb: 54.5,
      vibrationLevelMss: '< 2.5',
      weightWithoutBlowerKg: 10.13,
      weightWithBlowerKg: 11.32,
      packagingDimensionsCm: '64 x 46 x 36',
      noiseLevelLwaDb: 115,
      accessories: [
        'Llave sacabujía con destornillador - cabeza hexagonal',
        'Abrazaderas Ø 70',
        'Botella para preparación mezcla de combustible',
        'Tornillos TCEI M5x65',
      ],
      manufacturer: 'CIFARELLI S.P.A. MADE IN ITALY',
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Espolvoreador Cifarelli M1200PG',
    brand: 'Cifarelli',
    imageUrl: imgCifarelli[Math.round(Math.random() * (imgCifarelli.length - 1))],
    model: 'M1200PG',
    category: 'Espolvoreador',
    specs: {
      applications: [
        'Tratamientos con productos en polvo (como azufre ventilado)',
        'Aplicación de gránulos y semillas de arroz (en la siembra)',
      ],
      engineType:
        'CIFARELLI C7 monocilíndrico de 2 tiempos refrigerado por aire',
      displacementCc: 77,
      bore: 52,
      stroke: 36,
      maxPowerHp: 5,
      powerKw: 3.6,
      carburetor: 'WALBRO de membrana con cápsula',
      ignitionSystem: 'Encendido electrónico',
      sparkPlug: 'CHAMPION RCJ6Y',
      fuelTankCapacityL: 2.3,
      fuelType: 'Mezcla de gasolina y aceite para 2 tiempos',
      tankCapacityL: 27,
      flowRegulationLevels: 5,
      calibratedCasings: 5,
      airVolumeM3h: 1620,
      airSpeedMps: 105,
      acceleration: '378 Km/h / 235 MPH',
      handleType: 'Empuñadura con gatillo de aceleración',
      noiseLevelLpfaDb: 103,
      noiseLevelLwaDb: 115,
      vibrationLevelMss: '< 2.5',
      weightWithoutTubeKg: 11.35,
      weightWithTubeKg: 12.2,
      packagingDimensionsCm: '96 x 46 x 47',
      accessories: [
        'Llave sacabujía con destornillador - cabeza hexagonal',
        'Abrazaderas Ø 90',
        'Botella para preparación mezcla de combustible',
        'Tornillos TCEI M5x65',
        'Cadena de seguridad (cadena de tierra)',
      ],
      manufacturer: 'CIFARELLI S.P.A. MADE IN ITALY',
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motobomba Ducati DCW35251',
    brand: 'Ducati',
    imageUrl: imgDucati[Math.round(Math.random() * (imgDucati.length - 1))],
    model: 'DCW35251',
    category: 'Motobomba',
    specs: {
      engineType:
        'Monocilíndrico 4T OHC Refrigerado por aire / Single cylinder, 4-stroke, OHC, Air cooled',
      displacementCc: 79,
      maxPowerKw: 1.87,
      maxPowerHp: 2.5,
      maxRpm: 3800,
      starterType: 'Manual',
      ignitionSystem: 'Magneto transitorizado / Transistorized magneto',
      suctionPortInches: 1,
      suctionPortMm: 25,
      dischargePortInches: 1,
      dischargePortMm: 25,
      totalLiftM: 30,
      suctionLiftM: 6,
      maxPumpingRateLh: 6000,
      selfPrimeTimeSec: 120,
      suctionDischargeFitting: '1"x25mm Aluminum fitting, aluminum fixing nut',
      suctionFilter: '25mm Polypropylene',
      lengthMm: 410,
      widthMm: 310,
      heightMm: 400,
      dryWeightKg: 13.5,
      fuelTankCapacityL: 1.6,
      fuelAutonomyMin: 110,
      accessories: [
        'Rácor en aluminio, Tuerca en aluminio',
        'Filtro de succión 25mm en Polipropileno',
      ],
      manufacturer: 'DUCATI Licensed',
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Biotrituradora a Gasolina Ducati DWS65',
    brand: 'Ducati',
    imageUrl: imgDucati[Math.round(Math.random() * (imgDucati.length - 1))],
    model: 'DWS65',
    category: 'Biotrituradora',
    specs: {
      engineType: 'OHV (4T)',
      displacementCc: 196,
      maxPowerKw: 4.1,
      maxPowerHp: 6.5,
      primer: 'No',
      autoChoke: 'Sí',
      starterType: 'Manual / Recoil',
      ignitionSystem: 'Magneto transitorizado / Transistorized magneto',
      maxChippingDiameterInches: 4,
      maxChippingDiameterMm: 100,
      cuttingSystem: 'Trituración a rodillo / Drum shredding',
      numberOfBlades: 2,
      hopperFeedType: 'Manual',
      deflectingNozzleHeightM: 1.5,
      emergencyStop:
        'Sí, rodeando tolva de entrada / Yes, surrounding hopper mouth',
      transmission: 'Doble correa / Double belt',
      productivityM3h: '2.5 - 4',
      chassisMaterial: 'Acero / Steel',
      wheelDimensions: '4,10 / 3,5-4',
      fuelTankCapacityMl: 3600,
      soundLevelDbA: 98,
      netWeightKg: 95,
      grossWeightKg: 105,
      dimensionsMm: '870 x 890 x 565',
      containerCapacity: {
        twentyFoot: 48,
        fortyFoot: 'N/A',
        fortyHQ: 156,
      },
      eanCode: '8434691054912',
      additionalFeatures: [
        'Deflector de salida a 1,5m regulable en inclinación y orientable 360º',
        'Pie de apoyo más amplio para evitar el hundimiento en terreno blando',
        'Manillar de transporte de doble empuñadura',
        'Ruedas neumáticas grandes',
        'Ideal para troncos y material consistente',
        'Rotor de acero de gran durabilidad',
      ],
      manufacturer: 'DUCATI Licensed',
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Biotrituradora a Gasolina Ducati DWS150-DWS150E',
    brand: 'Ducati',
    imageUrl: imgDucati[Math.round(Math.random() * (imgDucati.length - 1))],
    model: 'DWS150-DWS150E',
    category: 'Biotrituradora',
    specs: {
      engineType: 'OHV (4T)',
      displacementCc: 420,
      maxPowerKw: 11.25,
      maxPowerHp: 15.0,
      starterType: 'Manual (DWS 150) - Eléctrico (DWS 150E)',
      ignitionSystem: 'Magneto transitorizado / Transistorized magneto',
      maxChippingDiameterInches: 4.7,
      maxChippingDiameterMm: 120,
      cuttingSystem: 'Trituración a rodillo / Drum shredding',
      numberOfBlades: 2,
      hopperFeedType: 'Manual',
      deflectingNozzleHeightM: 1.5,
      emergencyStop:
        'Sí, rodeando tolva de entrada / Yes, surrounding hopper mouth',
      transmission: 'Doble correa / Double belt',
      productivityM3h: '5 - 8',
      chassisMaterial: 'Acero / Steel',
      wheelDimensions: '16*6.5-8',
      fuelTankCapacityL: 6.5,
      oilTankCapacityL: 1.1,
      recommendedOilType: 'SAE10W-30',
      soundLevelDbA: 98,
      netWeightKg: 190,
      grossWeightKg: 205,
      dimensionsMm: '895 x 765 x 1200',
      containerCapacity: {
        twentyFoot: 18,
        fortyFoot: 'N/A',
        fortyHQ: 78,
      },
      eanCode: '8434691109216 - 8434691309760',
      additionalFeatures: [
        'Deflector de salida a 1,5m regulable en inclinación y orientable 360º',
        'Pie de apoyo más amplio para evitar el hundimiento en terreno blando',
        'Manillar de transporte de doble empuñadura',
        'Ruedas neumáticas grandes',
        'Ideal para troncos y material consistente',
        'Rotor de acero de gran durabilidad',
      ],
      manufacturer: 'DUCATI Licensed',
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motor 4T OHV Monocilíndrico Ducati DPE270Q',
    brand: 'Ducati',
    imageUrl: imgDucati[Math.round(Math.random() * (imgDucati.length - 1))],
    model: 'DPE270Q',
    category: 'Motor',
    specs: {
      engineType: 'OHV 4T Monocilíndrico',
      displacementCc: 270,
      maxPowerHp: 9,
      netPowerKw: 5.4,
      netPowerHp: 7.2,
      bore: 77,
      stroke: 58,
      compressionRatio: '8.5 : 1',
      netTorqueNm: 18,
      governorSystem: 'Centrífuga mecánica / Mechanical',
      airFilter: 'Húmedo bañado en aceite / Oil Bath',
      oilTankCapacityL: 1.1,
      fuelTankCapacityL: 6,
      fuelConsumptionGkwH: 374,
      starterType: 'Manual / Recoil',
      dimensionsMm: '490 x 430 x 530',
      containerCapacity: {
        twentyFoot: 432,
        fortyFoot: 900,
        fortyHQ: 1050,
      },
      netWeightKg: 27,
      grossWeightKg: 30,
      eanCode: '8434691309845',
      easyStart: 'Sí / Yes',
      manufacturer: 'DUCATI Licensed',
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Pulverizador Mochila DSP 2000',
    brand: 'Ducati',
    imageUrl: imgDucati[Math.round(Math.random() * (imgDucati.length - 1))],
    model: 'DSP3120S',
    category: 'Pulverizador',
    specs: {
      liquidTankCapacityL: 5.1,
      pistonTravelMm: 6.6,
      workingPressureBar: 2,
      workingPressureMpa: 0.2,
      netWeightKg: 20,
      grossWeightKg: 96,
      dimensionsMm: '410 x 210 x 570',
      containerCapacity: {
        twentyFoot: 360,
        fortyFoot: 1300,
        fortyHQ: 1500,
      },
      eanCode: '8434691037090',
      pumpType: 'Manual',
      manufacturer: 'DUCATI Licensed',
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motoazada Diesel DTL 11000D',
    brand: 'Ducati',
    imageUrl: imgDucati[Math.round(Math.random() * (imgDucati.length - 1))],
    model: 'DTL11000D',
    category: 'Motoazada Diesel',
    specs: {
      displacementCc: 418,
      maxPowerKw: 10,
      ratedPowerKw: 6.3,
      maxTorqueNm: 18.5,
      maxTorqueRpm: 2800,
      fuelTankCapacityL: 5.5,
      oilTankCapacityL: 1.65,
      airFilter: 'Oil Bath',
      engineDimensionsMm: '440 x 420 x 495',
      transmission: 'Gearbox',
      clutchType: 'Multidisc friction',
      gears: '4 + 2',
      workingWidthMm: '800 - 1000 - 1200 - 1500',
      handleType: 'Height regulation - Reversible',
      blades: 40,
      workingDepthMm: 320,
      security: 'Automatic stop',
      includedAccessories: [
        'Wheels 500 x 12mm',
        'Water pump',
        'PTO for extra accessories',
        'Fumigation pump',
        'Rear tine tiller',
        'Electric start',
        'Grass cutter',
        'Forage harvester',
        'Ditching machine',
      ],
      dimensionsMm: '1800 x 1150 x 1050',
      netWeightKg: 175,
      grossWeightKg: 190,
      containerCapacity: {
        twentyFoot: 40,
        fortyFoot: 88,
        fortyHQ: 1132,
      },
      eanCode: '8434691266735',
      manufacturer: 'DUCATI Licensed',
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motoazada Gasolina DTL 10000',
    brand: 'Ducati',
    imageUrl: imgDucati[Math.round(Math.random() * (imgDucati.length - 1))],
    model: 'DTL10000',
    category: 'Motoazada Gasolina',
    specs: {
      displacementCc: 212,
      maxPowerKw: 5.2,
      ratedPowerKw: 4.3,
      maxTorqueNm: 12.0,
      maxTorqueRpm: 2800,
      fuelTankCapacityL: 3.6,
      oilTankCapacityL: 1.6,
      airFilter: 'Oil Bath',
      engineDimensionsMm: '390 x 330 x 330',
      transmission: 'Gearbox',
      clutchType: 'Multidisc friction',
      gears: '4 + 2',
      workingWidthMm: '600 - 800 - 1000',
      handleType: 'Height regulation - Reversible',
      blades: 32,
      workingDepthMm: 320,
      security: 'Automatic stop',
      includedAccessories: [
        'Wheels 400 x 8mm',
        'Fuel purge lever',
        'Water pump',
        'PTO for extra accessories',
        'Fumigation pump',
        'Grass cutter',
        'Ditching machine',
      ],
      dimensionsMm: '1600 x 1000 x 1050',
      netWeightKg: 91,
      grossWeightKg: 101,
      containerCapacity: {
        twentyFoot: 48,
        fortyFoot: 96,
        fortyHQ: 144,
      },
      eanCode: '8434691266711',
      manufacturer: 'DUCATI Licensed',
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motobomba Aguas Limpias DCW502',
    brand: 'Ducati',
    imageUrl: imgDucati[Math.round(Math.random() * (imgDucati.length - 1))],
    model: 'DCW502',
    category: 'Motobomba Aguas Limpias',
    specs: {
      displacementCc: 212,
      maxPowerKw: 5.2,
      ratedPowerKw: 4.1,
      ratedPowerHp: 5.6,
      maxRpm: 3600,
      starter: 'Manual',
      ignition: 'Transistorized magneto',
      suctionPortInches: 2,
      dischargePortInches: 2,
      totalLiftM: 38,
      suctionLiftM: 7,
      maxPumpingRateLh: 35000,
      mechanicalSeal:
        'Ceramic seal bellow, Aluminum body pump, Cast Iron Impulsor with keyway',
      suctionDischargeFitting: '2"x50mm Aluminum fitting, aluminum fixing nut',
      hoseClamps: 3,
      suctionFilter: '50 mm Polyethylene',
      grilleOnEscape: true,
      lengthMm: 515,
      widthMm: 430,
      heightMm: 445,
      dryWeightKg: 25,
      grossWeightKg: 27,
      fuelTankCapacityL: 4,
      containerCapacity: {
        twentyFoot: 360,
        fortyFoot: 1300,
        fortyHQ: 1500,
      },
      eanCode: '8434691037090',
      manufacturer: 'DUCATI Licensed',
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motobomba Aguas Limpias DCW802',
    brand: 'Ducati',
    imageUrl: imgDucati[Math.round(Math.random() * (imgDucati.length - 1))],
    model: 'DCW802',
    category: 'Motobomba Aguas Limpias',
    specs: {
      displacementCc: 212,
      maxPowerKw: 5.2,
      ratedPowerKw: 4.1,
      ratedPowerHp: 5.6,
      maxRpm: 3600,
      starter: 'Manual',
      ignition: 'Transistorized magneto',
      suctionPortInches: 3,
      dischargePortInches: 3,
      totalLiftM: 32,
      suctionLiftM: 7,
      maxPumpingRateLh: 57000,
      mechanicalSeal:
        'Ceramic seal bellow, Aluminum body pump, Cast Iron Impulsor with keyway',
      suctionDischargeFitting: '3"x75mm aluminum fitting, aluminum fixing nut',
      hoseClamps: 3,
      suctionFilter: '75 mm Polyethylene',
      grilleOnEscape: true,
      lengthMm: 515,
      widthMm: 430,
      heightMm: 445,
      dryWeightKg: 28,
      grossWeightKg: 30,
      fuelTankCapacityL: 4,
      containerCapacity: {
        twentyFoot: 360,
        fortyFoot: 1300,
        fortyHQ: 1500,
      },
      eanCode: '8434691037106',
      manufacturer: 'DUCATI Licensed',
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motor 4T OHV Monocilíndrico DPE 390Q',
    brand: 'Ducati',
    imageUrl: imgDucati[Math.round(Math.random() * (imgDucati.length - 1))],
    model: 'DPE 390Q',
    category: 'Motor 4T OHV Monocilíndrico',
    specs: {
      displacementCc: 389,
      maxPowerHp: 13,
      ratedPowerKw: 10.4,
      ratedPowerHp: 14,
      takeStrength: 'Cylindrical with key 25,4 x 72,2 mm',
      boreStroke: '88 x 64 mm',
      compressionRatio: 8.0,
      netTorqueNm: 25,
      governorSystem: 'Centrifugal mechanical',
      airFilter: 'Semi-Dry',
      oilTankCapacityL: 1.1,
      fuelTankCapacityL: 6.5,
      fuelConsumption: '≤ 374 g/kw x h',
      starter: 'Manual / Recoil',
      lengthMm: 530,
      widthMm: 430,
      heightMm: 510,
      netWeightKg: 28,
      containerCapacity: {
        twentyFoot: 220,
        fortyFoot: 460,
        fortyHQ: 575,
      },
      eanCode: '8434691309852',
      manufacturer: 'DUCATI Licensed',
      optionalFeatures: ['Wet air filter in oil', 'Silent aluminized'],
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motor 4T OHV Monocilíndrico DPE 210Q',
    brand: 'Ducati',
    imageUrl: imgDucati[Math.round(Math.random() * (imgDucati.length - 1))],
    model: 'DPE 210Q',
    category: 'Motor 4T OHV Monocilíndrico',
    specs: {
      displacementCc: 212,
      maxPowerHp: 7,
      ratedPowerKw: 5.33,
      ratedPowerHp: 7.0,
      takeStrength: 'Cylindrical with key 19,05 x 58,5 mm',
      boreStroke: '70 x 55 mm',
      compressionRatio: 8.5,
      netTorqueNm: 12,
      governorSystem: 'Centrifugal mechanical',
      airFilter: 'Semi-Dry',
      oilTankCapacityL: 0.6,
      fuelTankCapacityL: 3.6,
      fuelConsumption: '≤ 395 g/kw x h',
      starter: 'Manual / Recoil',
      lengthMm: 400,
      widthMm: 375,
      heightMm: 380,
      netWeightKg: 16,
      containerCapacity: {
        twentyFoot: 490,
        fortyFoot: 1020,
        fortyHQ: 1020,
      },
      eanCode: '8434691309838',
      manufacturer: 'DUCATI Licensed',
      optionalFeatures: ['Wet air filter in oil'],
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Pulverizador Mochila Líquidos DSP 2500',
    brand: 'Ducati',
    imageUrl: imgDucati[Math.round(Math.random() * (imgDucati.length - 1))],
    model: 'DSP 2500',
    category: 'Pulverizador Mochila Líquidos',
    specs: [
      {
        displacementCc: 25.4,
        maxPowerKw: 0.7,
        maxPowerHp: 1,
        speedRpm: 7500,
        fuelTankCapacityL: 0.65,
        liquidTankCapacityL: 20,
        liquidFlowPerHoseLMin: '6 - 7',
        maxPressurePsi: 500,
        workingPressureBar: 25,
        netWeightKg: 9,
        grossWeightKg: 11,
        dimensionsMm: '425 x 375 x 550',
        containerCapacity: {
          twentyFoot: 325,
          fortyFoot: 740,
          fortyHQ: 780,
        },
        eanCode: '8434691036055',
        features: ['Pressure control knob', 'Reinforced strap harness'],
      },
      {
        displacementCc: 25.4,
        maxPowerKw: 0.7,
        maxPowerHp: 1,
        speedRpm: 7500,
        fuelTankCapacityL: 0.65,
        liquidTankCapacityL: 15,
        liquidFlowPerHoseLMin: '6 - 7',
        maxPressurePsi: 500,
        workingPressureBar: 25,
        netWeightKg: 9,
        grossWeightKg: 11,
        dimensionsMm: '425 x 350 x 535',
        containerCapacity: {
          twentyFoot: 350,
          fortyFoot: 800,
          fortyHQ: 850,
        },
        eanCode: '8434691036109',
        features: ['Pressure control knob', 'Reinforced strap harness'],
      },
      {
        displacementCc: 25.4,
        maxPowerKw: 0.75,
        maxPowerHp: 1,
        speedRpm: 7000,
        fuelTankCapacityL: 0.75,
        liquidTankCapacityL: 25,
        liquidFlowPerHoseLMin: '4 - 5',
        maxPressurePsi: 500,
        workingPressureBar: 25,
        netWeightKg: 9.5,
        grossWeightKg: 11.8,
        dimensionsMm: '490 x 340 x 645',
        containerCapacity: {
          twentyFoot: 220,
          fortyFoot: 470,
          fortyHQ: 560,
        },
        eanCode: '8434691305182',
        features: [
          'Pressure control knob',
          'Reinforced strap harness',
          'Two Triple Nozzle Lances',
        ],
      },
    ],
    manufacturer: 'DUCATI Licensed',
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Planta de Emergencia EZ6500CXS',
    brand: 'Ducati',
    imageUrl: imgDucati[Math.round(Math.random() * (imgDucati.length - 1))],
    model: 'EZ6500CXS',
    category: 'Planta de Emergencia',
    specs: [
      {
        maxPowerKVA: 6.5,
        ratedPowerKVA: 5.5,
        voltageV: 220,
        engineModel: 'GX390',
        fuelType: 'Gasolina de 90',
        fuelTankCapacityL: 15.5,
        oilTankCapacityL: 1.1,
        continuousOperationHours: 5.4,
        ignitionSystem: 'Magneto Transistorizado',
        coolingSystem: 'Forzada de aire',
        cylinderCount: 1,
        displacementCc: 389,
        dimensionsMm: '685 x 535 x 540',
        dryWeightKg: 80,
        accessoriesIncluded: ['Aceite', 'Manual de uso'],
        application: 'Iluminación, Planta de Emergencia',
        startSystem: 'Eléctrico',
      },
    ],
    manufacturer: 'DUCATI Licensed',
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motor GP160H QH1',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'GP160H QH1',
    category: 'Motor Multipropósito',
    specs: [
      {
        maxPowerHp: 5.5,
        ratedPowerHp: 4.8,
        rpm: 3600,
        compressionRatio: '8.5:1',
        fuelTankCapacityL: 3.1,
        oilTankCapacityL: 0.58,
        continuousOperationHours: 7,
        ignitionSystem: 'Magneto Transistorizado',
        coolingSystem: 'Aire Forzado',
        shaftType: 'Chavetero',
        sparkPlugGapMm: '0.7 - 0.8',
        cylinderCount: 1,
        displacementCc: 163,
        dimensionsMm: '314 x 363 x 335',
        dryWeightKg: 14.9,
        use: 'Agricultura, Minería Artesanal, Ganadería, Jardinería, Construcción',
        application:
          'Motobomba, Despulpadora de Café, Molino de Cereales, Lavador de Minerales, etc.',
        accessoriesIncluded: [
          'Aceite',
          'Manual de Usuario',
          'Certificado de Garantía',
          'Kit de Herramientas',
        ],
        warranty: '1 Año',
      },
    ],
    manufacturer: 'Honda',
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motor GX430',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'GX430 QX',
    category: 'Motor Multifuncional',
    specs: [
      {
        maxPowerHp: 14,
        ratedPowerKw: 9.6,
        ratedPowerHp: 13.05,
        rpm: 3000,
        compressionRatio: '9.0',
        coolingSystem: 'Aire Forzado',
        ignitionSystem: 'Magneto Transistorizado',
        carburetor: 'Válvula de mariposa tipo horizontal',
        airFilter: 'Tipo dual',
        lubricationSystem: 'Salpicadura forzada',
        oilTankCapacityL: 1.1,
        starterSystem: 'Cuerda Retráctil',
        recommendedFuel: 'Gasolina sin plomo superior a 86 oct',
        fuelTankCapacityL: 6.1,
        displacementCc: 425,
        boreAndStroke: '88.0 x 70.0 mm (3.46 x 2.75 in)',
        dimensionsMm: '387 x 469 x 453',
        dryWeightKg: 32,
        applications: [
          'Mezcladora',
          'Generadores',
          'Motobombas',
          'Cortadora de concreto',
          'Hidrolavadora de presión',
          'Compactadora',
        ],
      },
    ],
    manufacturer: 'Honda',
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Bomba Tragasólidos WT30XK4',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'WT30XK4',
    category: 'Bomba Tragasólidos',
    specs: [
      {
        pumpType: 'Tragasólidos',
        suctionAndDischargeDiameterInches: 3,
        maxTotalLiftM: 27,
        maxSuctionLiftM: 8,
        maxFlowLMin: 1200,
        widthMm: 660,
        dryWeightKg: 61,
        lengthMm: 495,
        heightMm: 515,
        engineModel: 'GX270T2',
        engineType: 'Monocilíndrico',
        valveSystem: '4 tiempos OHV',
        maxPowerHp: 9,
        maxPowerRpm: 3600,
        warrantyYears: 2,
        performanceCurves: [200, 400, 800, 600, 1000, 1200, 1400], // Puede representarse en una gráfica si se desea
        applications: [
          'Bomba de aguas sucias',
          'Industria de construcción',
          'Agricultura',
        ],
      },
    ],
    manufacturer: 'Honda',
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Bomba Autocebante WL20XH',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'WL20XH',
    category: 'Bomba Autocebante',
    specs: [
      {
        pumpType: 'Autocebante',
        suctionAndDischargeDiameterInches: 2,
        maxTotalLiftM: 32,
        maxSuctionLiftM: 7.5,
        maxFlowLMin: 670,
        widthMm: 385,
        dryWeightKg: 24,
        lengthMm: 490,
        heightMm: 410,
        engineModel: 'GP160H',
        engineType: 'Monocilíndrico',
        valveSystem: '4-Tiempos, OHV',
        maxPowerHp: 5.5,
        maxPowerRpm: 3600,
        warrantyYears: 1,
        performanceCurves: [0, 100, 200, 300, 400, 500, 600, 700],
        accessoriesIncluded: [
          'Kit de empaques',
          '3 abrazaderas',
          '2 bridas de ajuste',
          '2 acoples de manguera',
          '2 empaques de acople de manguera',
          '1 canastilla',
          '1 sacabujías con palanca',
        ],
        applications: [
          'Bomba de aguas limpias',
          'Industria de construcción',
          'Agricultura',
        ],
      },
    ],
    manufacturer: 'Honda',
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Bomba Autocebante WL20XH',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'WL20XH',
    category: 'Bomba Autocebante',
    specs: [
      {
        pumpType: 'Autocebante',
        suctionAndDischargeDiameterInches: 2,
        maxTotalLiftM: 32,
        maxSuctionLiftM: 7.5,
        maxFlowLMin: 670,
        widthMm: 385,
        dryWeightKg: 24,
        lengthMm: 490,
        heightMm: 410,
        engineModel: 'GP160H',
        engineType: 'Monocilíndrico',
        valveSystem: '4-Tiempos, OHV',
        maxPowerHp: 5.5,
        maxPowerRpm: 3600,
        warrantyYears: 1,
        performanceCurves: [0, 100, 200, 300, 400, 500, 600, 700],
        accessoriesIncluded: [
          'Kit de empaques',
          '3 abrazaderas',
          '2 bridas de ajuste',
          '2 acoples de manguera',
          '2 empaques de acople de manguera',
          '1 canastilla',
          '1 sacabujías con palanca',
        ],
        applications: [
          'Bomba de aguas limpias',
          'Industria de construcción',
          'Agricultura',
        ],
      },
    ],
    manufacturer: 'Honda',
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Bomba Autocebante WL20XH',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'WL20XH',
    category: 'Bomba Autocebante',
    specs: [
      {
        pumpType: 'Autocebante',
        suctionAndDischargeDiameterInches: 2,
        maxTotalLiftM: 32,
        maxSuctionLiftM: 7.5,
        maxFlowLMin: 670,
        widthMm: 385,
        dryWeightKg: 24,
        lengthMm: 490,
        heightMm: 410,
        engineModel: 'GP160H',
        engineType: 'Monocilíndrico',
        valveSystem: '4-Tiempos, OHV',
        maxPowerHp: 5.5,
        maxPowerRpm: 3600,
        warrantyYears: 1,
        performanceCurves: [0, 100, 200, 300, 400, 500, 600, 700],
        accessoriesIncluded: [
          'Kit de empaques',
          '3 abrazaderas',
          '2 bridas de ajuste',
          '2 acoples de manguera',
          '2 empaques de acople de manguera',
          '1 canastilla',
          '1 sacabujías con palanca',
        ],
        applications: [
          'Bomba de aguas limpias',
          'Industria de construcción',
          'Agricultura',
        ],
      },
    ],
    manufacturer: 'Honda',
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Bomba Autocebante WB30XH2',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'WB30XH2',
    category: 'Bomba Autocebante',
    specs: [
      {
        pumpType: 'Autocebante',
        suctionAndDischargeDiameterInches: 3,
        maxTotalLiftM: 28,
        maxSuctionLiftM: 8,
        maxFlowLMin: 1100,
        widthMm: 385,
        dryWeightKg: 27,
        lengthMm: 510,
        heightMm: 435,
        engineModel: 'GX160H1',
        engineType: 'Monocilíndrico',
        valveSystem: '4-Tiempos, OHV',
        maxPowerHp: 5.5,
        maxPowerRpm: 3600,
        warrantyYears: 2,
        performanceCurves: [200, 400, 600, 800, 1000],
        accessoriesIncluded: [
          '3 abrazaderas',
          '2 bridas de ajuste',
          '2 acoples de manguera',
          '2 empaques de acople de manguera',
          '1 canastilla',
          '1 sacabujías con palanca',
        ],
        applications: ['Bomba de aguas limpias', 'Construcción', 'Agricultura'],
      },
    ],
    manufacturer: 'Honda',
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Bomba Tragasólidos WT40XK3',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'WT40XK3',
    category: 'Bomba Tragasólidos',
    specs: [
      {
        pumpType: 'Tragasólidos',
        suctionAndDischargeDiameterInches: 4,
        maxTotalLiftM: 25,
        maxSuctionLiftM: 8,
        maxFlowLMin: 1600,
        widthMm: 535,
        dryWeightKg: 78,
        lengthMm: 735,
        heightMm: 565,
        engineModel: 'GX390T2',
        engineType: 'Monocilíndrico',
        valveSystem: '4-Tiempos, OHV',
        maxPowerHp: 13,
        maxPowerRpm: 3600,
        warrantyYears: 2,
        performanceCurves: [200, 400, 600, 800, 1000],
        accessoriesIncluded: [
          '3 abrazaderas',
          '2 bridas de ajuste',
          '2 acoples de manguera',
          '2 empaques de acople de manguera',
          '1 canastilla',
        ],
        applications: ['Tragado de sólidos', 'Construcción', 'Agricultura'],
      },
    ],
    manufacturer: 'Honda',
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Generador EG1000N',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'EG1000N',
    category: 'Generador',
    specs: [
      {
        maxOutputVA: 1000,
        nominalOutputVA: 900,
        frequencyHz: 60,
        outputVoltageV: 220,
        engineModel: 'GX80D',
        engineType: '4 tiempos - OHV',
        valveSystem: 'Monocilíndrico',
        displacementCm3: 79.7,
        fuelTankCapacityL: 3.6,
        continuousOperationHours: 5.5,
        startSystem: 'Arranque retractil o de retroceso',
        noiseLevelDb: 'Bajo carga nominal a 7m',
        fuelType: 'Gasolina de 90',
        warrantyYears: 2,
        phase: 'Monofásico',
        voltageRegulator: 'No',
        ecoThrottleRegulator: 'No',
        batteryCharger: 'No',
        acCircuitBreaker: 'No',
        voltmeter: 'No',
        fuelGauge: 'No',
        oilAlert: 'No',
        electricStart: 'No',
        overloadAlarm: 'No',
        engineOilCapacityL: 0.36,
        recommendedOil: 'SAE 10W-30 API',
        accessoriesIncluded: ['1 enchufe 15A/250V', '1 sacabujías con palanca'],
        applications: [
          'Iluminación',
          'Uso doméstico',
          'Agricultura',
          'Recreación',
        ],
        dimensions: {
          lengthMm: 376,
          widthMm: 301,
          heightMm: 430,
        },
        dryWeightKg: 22.5,
      },
    ],
    manufacturer: 'Honda',
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Generador EG5000CX',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'EG5000CX',
    category: 'Generador',
    specs: [
      {
        maxOutputVA: 5000,
        nominalOutputVA: 4500,
        frequencyHz: 60,
        outputVoltageV: '120/240',
        dcNominalCurrentA: 8.3,
        engineModel: 'GX340H1',
        engineType: '4 tiempos - OHC',
        valveSystem: 'Monocilíndrico',
        displacementCm3: 337,
        fuelTankCapacityL: 24,
        continuousOperationHours: 8.5,
        startSystem: 'Arranque retractil o de retroceso',
        noiseLevelDb: 101,
        fuelType: 'Gasolina de 90',
        warrantyYears: 2,
        phase: 'Monofásico',
        voltageRegulator: 'Digital',
        ecoThrottleRegulator: 'No',
        batteryCharger: 'No',
        acCircuitBreaker: 'Sí',
        voltmeter: 'Sí',
        fuelGauge: 'No',
        oilAlert: 'No',
        electricStart: 'No',
        overloadAlarm: 'No',
        engineOilCapacityL: 1.1,
        recommendedOil: 'SAE 10W-30 API',
        accessoriesIncluded: [
          '2 enchufes 15A/125V',
          '1 enchufe 30A-125/250V',
          '1 enchufe 30A/125V',
          '1 sacabujías con palanca',
        ],
        applications: [
          'Iluminación',
          'Herramientas Eléctricas',
          'Uso doméstico',
          'Minería',
          'Construcción',
          'Agricultura',
        ],
        dimensions: {
          lengthMm: 681,
          widthMm: 530,
          heightMm: 571,
        },
        dryWeightKg: 82.5,
      },
    ],
    manufacturer: 'Honda',
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Generador EG6500CXS-S1H',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'EG6500CXS-S1H',
    category: 'Generador',
    specs: [
      {
        maxOutputVA: 6500,
        nominalOutputVA: 5500,
        frequencyHz: 60,
        outputVoltageV: '220',
        dcNominalCurrentA: 8.3,
        engineModel: 'GX390H1',
        engineType: '4 tiempos - OHC',
        valveSystem: 'Monocilíndrico',
        displacementCm3: 389,
        fuelTankCapacityL: 24,
        continuousOperationHours: 7,
        startSystem:
          'Arranque retractil o de retroceso y arranque automatico a batería',
        noiseLevelDb: 102,
        fuelType: 'Gasolina de 90',
        warrantyYears: 2,
        phase: 'Monofásico',
        voltageRegulator: 'Digital',
        ecoThrottleRegulator: 'No',
        batteryCharger: 'Sí',
        acCircuitBreaker: 'Sí',
        voltmeter: 'Sí',
        fuelGauge: 'Sí',
        oilAlert: 'Sí',
        electricStart: 'Sí',
        overloadAlarm: 'No',
        engineOilCapacityL: 1.1,
        recommendedOil: 'SAE 10W-30 API',
        accessoriesIncluded: [
          '2 enchufes 20A/250V',
          '1 sacabujías con palanca',
        ],
        applications: [
          'Iluminación',
          'Herramientas Eléctricas',
          'Uso doméstico',
          'Minería',
          'Construcción',
          'Agricultura',
        ],
        dimensions: {
          lengthMm: 844,
          widthMm: 530,
          heightMm: 571,
        },
        dryWeightKg: 87,
      },
    ],
    manufacturer: 'Honda',
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Generador EM10000K1',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'EM10000K1',
    category: 'Generador',
    specs: [
      {
        maxOutputVA: 10000,
        nominalOutputVA: 9000,
        frequencyHz: 60,
        outputVoltageV: '120 / 240',
        dcNominalCurrentA: null, // No disponible
        engineModel: 'GX630H',
        engineType: '4 tiempos - OHV',
        valveSystem: 'Bicilíndrico - V TWIN',
        displacementCm3: 688,
        fuelTankCapacityL: 31,
        continuousOperationHours: 5.3,
        startSystem: 'Arranque automático a batería',
        noiseLevelDb: 103.4,
        fuelType: 'Gasolina de 90',
        warrantyYears: 2,
        phase: 'Monofásico',
        voltageRegulator: 'Digital',
        ecoThrottleRegulator: 'No',
        batteryCharger: 'No',
        acCircuitBreaker: 'Sí',
        voltmeter: 'No',
        fuelGauge: 'Sí',
        oilAlert: 'No',
        electricStart: 'Sí',
        overloadAlarm: 'No',
        engineOilCapacityL: 1.5,
        recommendedOil: 'SAE 10W-30 API',
        accessoriesIncluded: [
          '4 enchufes 15A / 125V',
          '1 enchufe 50A/125-250V',
          '1 enchufe 30A/125-250V',
          '1 enchufe 30A/125V',
          '1 sacabujías con palanca',
          '1 embudo para aceite',
          '1 batería',
        ],
        applications: [
          'Iluminación',
          'Herramientas Eléctricas',
          'Uso doméstico',
          'Minería',
          'Construcción',
          'Agricultura',
        ],
        dimensions: {
          lengthMm: 973,
          widthMm: 552,
          heightMm: 695,
        },
        dryWeightKg: 162.3,
      },
    ],
    manufacturer: 'Honda',
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Generador GXH50',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'GXH50',
    category: 'Generador',
    specs: {
      applications: [
        'Recreación',
        'Equipos Electrónicos',
        'Unidades Portátiles',
        'Equipos especializados',
        'Equipos de Precisión',
      ],
      engineType: '4 tiempos - OHC',
      valveSystem: 'Monocilíndrico',
      displacementCc: 50,
      fuelTankCapacityL: 2.3,
      continuousOperationHours: 3.9,
      startSystem: 'Arranque retractil o de retroceso',
      noiseLevelDb: 86,
      fuelType: 'Gasolina de 90',
      regulatorType: 'Inversor',
      ecoThrottle: true,
      weightKg: 13,
      oilCapacityL: 0.25,
      recommendedOil: 'SAE 10W-30 API',
      dimensions: {
        length: 450,
        width: 240,
        height: 380,
      },
      accessories: ['2 enchufes', '1 sacabujías con palanca'],
      warranty: '1 Año',
      voltageOutputV: 220,
      maxPowerVA: 1000,
      nominalPowerVA: 900,
      frequencyHZ: 60,
      voltageDC: 8,
      oilAlert: true,
      overloadAlarm: false,
      voltMeter: false,
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Generador GXR120T',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'GXR120T',
    category: 'Generador',
    specs: {
      applications: [
        'Recreación',
        'Equipos Electrónicos',
        'Unidades Portátiles',
        'Equipos especializados',
        'Equipos de Precisión',
      ],
      engineType: '4 tiempos - OHV',
      valveSystem: 'Monocilíndrico',
      displacementCc: 121,
      fuelTankCapacityL: 3.6,
      continuousOperationHours: 3.2,
      startSystem: 'Arranque retractil o de retroceso',
      noiseLevelDb: 90,
      fuelType: 'Gasolina de 90',
      regulatorType: 'Inversor',
      ecoThrottle: true,
      weightKg: 21.1,
      oilCapacityL: 0.44,
      recommendedOil: 'SAE 10W-30 API',
      dimensions: {
        length: 519,
        width: 290,
        height: 425,
      },
      accessories: ['2 enchufes', '1 sacabujías con palanca'],
      warranty: '1 Año',
      voltageOutputV: 220,
      maxPowerVA: 2200,
      nominalPowerVA: 1800,
      frequencyHZ: 60,
      voltageDC: 8.3,
      oilAlert: true,
      overloadAlarm: false,
      voltMeter: false,
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Generador GP200',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'GP200',
    category: 'Generador',
    specs: {
      applications: [
        'Iluminación',
        'Herramientas Eléctricas',
        'Uso doméstico',
        'Minería',
        'Construcción',
        'Agricultura',
      ],
      engineType: '4 tiempos - OHV',
      valveSystem: 'Monocilíndrico',
      displacementCc: 196,
      fuelTankCapacityL: 11.5,
      continuousOperationHours: 6.9,
      startSystem: 'Arranque retractil o de retroceso',
      noiseLevelDb: null, // No especificado
      fuelType: 'Gasolina de 90',
      regulatorType: 'Analógico',
      ecoThrottle: false,
      weightKg: 44,
      oilCapacityL: 0.6,
      recommendedOil: 'SAE 10W-30 API',
      dimensions: {
        length: 595,
        width: 435,
        height: 485,
      },
      accessories: ['Kit de ruedas', '2 enchufes 250V/30A', '1 sacabujías'],
      warranty: '1 Año',
      voltageOutputV: 220,
      maxPowerVA: 3000,
      nominalPowerVA: 2600,
      frequencyHZ: 60,
      voltageDC: null, // No especificado
      oilAlert: true,
      overloadAlarm: false,
      voltMeter: true,
      fuelMeter: true,
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motor GP200H',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'GP200H',
    category: 'Motor',
    specs: {
      engineType: '4 tiempos monocilíndrico',
      valveSystem: 'OHV',
      displacementCc: 196,
      maxPowerHp: 6.5,
      maxPowerRpm: 3600,
      nominalPowerHp: 5.5,
      nominalPowerRpm: 3600,
      maxTorqueNm: 12.4,
      maxTorqueRpm: 2500,
      airFilterType: 'Dual',
      fuelTankCapacityL: 3.1,
      fuelConsumptionLh: 1.7,
      fuelType: 'Gasolina de 90',
      recommendedOil: 'SAE 10W-30 API - HONDA',
      dimensions: {
        length: 323,
        width: 378,
        height: 335,
      },
      weightKg: 16.0,
      accessories: [],
      warranty: '1 Año',
      strokeDiameterMm: '68 x 45',
      compressionRatio: '8.5 : 1',
      shaftType: 'Horizontal recto',
      coolingSystem: 'Aire Forzado',
      ignitionSystem: 'Magneto transistorizado',
      ignitionTime: 'AMPS 20°',
      sparkPlugs: 'BPR6ES (NGK) / W20EPR-U (DENSO)',
      lubricationSystem: 'Salpicadura',
      startSystem: 'A cuerda retráctil',
      stopSystem: 'Circuito primario, ignición a tierra',
      oilCapacityCc: 600,
      oilAlertSystem: false,
      recommendedOperatingRpmRange: '2000-3600',
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motor GX120T3',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'GX120T3',
    category: 'Motor',
    specs: {
      engineType: '4 tiempos monocilíndrico',
      valveSystem: 'OHV',
      displacementCc: 122,
      maxPowerHp: 4,
      maxPowerRpm: 3600,
      nominalPowerHp: 3.2,
      nominalPowerRpm: 3600,
      maxTorqueNm: 7.5,
      maxTorqueRpm: 2500,
      airFilterType: 'Dual silencioso',
      fuelTankCapacityL: 2,
      fuelConsumptionLh: 1.0,
      fuelType: 'Gasolina de 90 oct',
      recommendedOil: 'SAE 10W-30 API - HONDA',
      dimensions: {
        length: 305,
        width: 346,
        height: 333,
      },
      weightKg: 13.2,
      accessories: [],
      warranty: '',
      strokeDiameterMm: '60 x 43.5',
      compressionRatio: '8.3 : 1',
      shaftType: 'Horizontal recto',
      coolingSystem: 'Aire Forzado',
      ignitionSystem: 'Magneto transistorizado',
      ignitionTime: 'B.T.D.C. 23°',
      sparkPlugs: 'BP6ES (NGK)/ W20EP-U (DENSO)',
      lubricationSystem: 'Salpicadura',
      startSystem: 'A cuerda retráctil',
      stopSystem: 'Circuito primario, ignición a tierra',
      oilCapacityCc: 560,
      oilAlertSystem: false,
      recommendedOperatingRpmRange: '2000-3600',
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motor GX160H2',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'GX160H2',
    category: 'Motor',
    specs: {
      engineType: '4 tiempos monocilíndrico',
      valveSystem: 'OHV',
      displacementCc: 163,
      maxPowerHp: 5.5,
      maxPowerRpm: 3600,
      nominalPowerHp: 4.8,
      nominalPowerRpm: 3600,
      maxTorqueNm: 10.3,
      maxTorqueRpm: 2500,
      airFilterType: 'Dual',
      fuelTankCapacityL: 3.1,
      fuelConsumptionLh: 1.4,
      fuelType: 'Gasolina de 90',
      recommendedOil: 'SAE 10W-30 API - HONDA',
      dimensions: {
        length: 312,
        width: 362,
        height: 346,
      },
      weightKg: 15.0,
      accessories: [],
      warranty: '2 Años',
      strokeDiameterMm: '68 x 45',
      compressionRatio: '8.5 : 1',
      shaftType: 'Horizontal recto',
      coolingSystem: 'Aire Forzado',
      ignitionSystem: 'Magneto transistorizado',
      ignitionTime: 'B.T.D.C. 25°',
      sparkPlugs: 'BPR6ES (NGK) / W20EPR-U (DENSO)',
      lubricationSystem: 'Salpicadura',
      startSystem: 'A cuerda retráctil',
      stopSystem: 'Circuito primario, ignición a tierra',
      oilCapacityCc: 580,
      oilAlertSystem: true,
      recommendedOperatingRpmRange: '2000-3600',
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motor GX200T2',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'GX200T2',
    category: 'Motor',
    specs: {
      engineType: '4 tiempos monocilíndrico',
      valveSystem: 'OHV',
      displacementCc: 196,
      maxPowerHp: 6.5,
      maxPowerRpm: 3600,
      nominalPowerHp: 5.5,
      nominalPowerRpm: 3600,
      maxTorqueNm: 23.6,
      maxTorqueRpm: 1250,
      airFilterType: 'Semi-seco',
      fuelTankCapacityL: 3.1,
      fuelConsumptionLh: 1.7,
      fuelType: 'Gasolina de 90',
      recommendedOil: 'SAE 10W-30 API - HONDA',
      dimensions: {
        length: 311,
        width: 375,
        height: 335,
      },
      weightKg: 16.6,
      accessories: [],
      warranty: null, // No especificada
      strokeDiameterMm: '68 x 45',
      compressionRatio: '8.5 : 1',
      shaftType: 'Horizontal recto',
      coolingSystem: 'Aire Forzado',
      ignitionSystem: 'Magneto transistorizado',
      ignitionTime: null, // No especificado
      sparkPlugs: null, // No especificado
      lubricationSystem: 'Salpicadura',
      startSystem: 'A cuerda retráctil',
      stopSystem: 'Circuito primario, ignición a tierra',
      oilCapacityCc: 600,
      oilAlertSystem: null, // No especificado
      recommendedOperatingRpmRange: '2000-3600', // Rango recomendado de operación
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motor GX200T2',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'GX200T2',
    category: 'Motor',
    specs: {
      engineType: '4 tiempos monocilíndrico',
      valveSystem: 'OHV',
      displacementCc: 196,
      maxPowerHp: 6.5,
      maxPowerRpm: 1800,
      nominalPowerHp: 5.5,
      nominalPowerRpm: 1800,
      maxTorqueNm: 23.6,
      maxTorqueRpm: 1250,
      airFilterType: 'Semi-seco',
      fuelTankCapacityL: 3.1,
      fuelConsumptionLh: 1.7,
      fuelType: 'Gasolina de 90',
      recommendedOil: 'SAE 10W-30 API - HONDA',
      dimensions: {
        length: 311,
        width: 375,
        height: 335,
      },
      weightKg: 16.6,
      accessories: [],
      warranty: null, // No especificada
      strokeDiameterMm: '68 x 45',
      compressionRatio: '8.5 : 1',
      shaftType: 'Horizontal recto',
      coolingSystem: 'Aire Forzado',
      ignitionSystem: 'Magneto transistorizado',
      ignitionTime: null, // No especificado
      sparkPlugs: null, // No especificado
      lubricationSystem: 'Salpicadura',
      startSystem: 'A cuerda retráctil',
      stopSystem: 'Circuito primario, ignición a tierra',
      oilCapacityCc: 600,
      oilAlertSystem: null, // No especificado
      additionalFeatures: null, // No especificados
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motor GX270H2',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'GX270H2',
    category: 'Motor',
    specs: {
      engineType: '4 tiempos monocilíndrico',
      valveSystem: 'OHV',
      displacementCc: 270,
      maxPowerHp: 9,
      maxPowerRpm: 3600,
      nominalPowerHp: 8.4,
      nominalPowerRpm: 3600,
      maxTorqueNm: 18.3,
      maxTorqueRpm: 2500,
      airFilterType: 'Dual',
      fuelTankCapacityL: 5.3,
      fuelConsumptionLh: 2.8,
      fuelType: 'Gasolina de 90',
      recommendedOil: 'SAE 10W-30 API - HONDA',
      dimensions: {
        length: 381,
        width: 428,
        height: 410,
      },
      weightKg: 25.2,
      accessories: [],
      warranty: '2 Años',
      strokeDiameterMm: '77 x 58',
      compressionRatio: '8.5 : 1',
      shaftType: 'Horizontal recto',
      coolingSystem: 'Aire Forzado',
      ignitionSystem: 'CDI',
      ignitionTime: 'B.T.D.C. 10°',
      sparkPlugs: 'BPR6ES (NGK) / W20EPR-U (DENSO)',
      lubricationSystem: 'Salpicadura',
      startSystem: 'A cuerda retráctil',
      stopSystem: 'Circuito primario, ignición a tierra',
      oilCapacityCc: 1100,
      oilAlertSystem: 'Sí',
      additionalFeatures: null, // No especificados
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motor GX35T',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'GX35T',
    category: 'Motor',
    specs: {
      engineType: '4 tiempos monocilíndrico',
      valveSystem: 'OHC',
      displacementCc: 35.8,
      maxPowerHp: 1.6,
      maxPowerRpm: 7000,
      nominalPowerHp: 1.38,
      nominalPowerRpm: 7000,
      maxTorqueNm: 1.6,
      maxTorqueRpm: 5500,
      airFilterType: 'Semi-seco',
      fuelTankCapacityL: 0.65,
      fuelConsumptionLh: 0.45,
      fuelType: 'Gasolina de 90 oct',
      recommendedOil: 'SAE 10W-30 API - HONDA',
      dimensions: {
        length: 198,
        width: 234,
        height: 240,
      },
      weightKg: 3.46,
      accessories: [],
      warranty: '1 Año',
      strokeDiameterMm: '39 x 30',
      compressionRatio: '8:1',
      shaftType: 'Horizontal recto',
      coolingSystem: 'Aire Forzado',
      ignitionSystem: 'Magneto transistorizado',
      ignitionTime: '27° A.P.M.S. (fija)',
      sparkPlugs: 'CMR5H (NGK)',
      lubricationSystem: 'Salpicadura',
      startSystem: 'A cuerda retráctil',
      stopSystem: 'Circuito primario, ignición a tierra',
      oilCapacityCc: 100,
      oilAlertSystem: null, // No especificado
      additionalFeatures: null, // No especificados
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motor GX390H2',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'GX390H2',
    category: 'Motor',
    specs: {
      engineType: '4 tiempos monocilíndrico',
      valveSystem: 'OHV',
      displacementCc: 389,
      maxPowerHp: 13,
      maxPowerRpm: 3600,
      nominalPowerHp: 11.7,
      nominalPowerRpm: 3600,
      maxTorqueNm: 26.5,
      maxTorqueRpm: 2500,
      airFilterType: 'Dual',
      fuelTankCapacityL: 6.1,
      fuelConsumptionLh: 3.7,
      fuelType: 'Gasolina de 90',
      recommendedOil: 'SAE 10W-30 API - HONDA',
      dimensions: {
        length: 406,
        width: 460,
        height: 435,
      },
      weightKg: 31.5,
      accessories: [],
      warranty: '2 Años',
      strokeDiameterMm: '88 x 64',
      compressionRatio: '8.2:1',
      shaftType: 'Horizontal recto',
      coolingSystem: 'Aire Forzado',
      ignitionSystem: 'CDI',
      ignitionTime: 'B.T.D.C. 10°',
      sparkPlugs: 'BPR6ES (NGK) / W20EPR-U (DENSO)',
      lubricationSystem: 'Salpicadura',
      startSystem: 'A cuerda retráctil',
      stopSystem: 'Circuito primario, ignición a tierra',
      oilCapacityCc: 1100,
      oilAlertSystem: 'Sí',
      additionalFeatures: null, // No especificados
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motor GX50T',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'GX50T',
    category: 'Motor',
    specs: {
      engineType: '4 tiempos monocilíndrico',
      valveSystem: 'OHC',
      displacementCc: 47.9,
      maxPowerHp: 2.2,
      maxPowerRpm: 7000,
      nominalPowerHp: 1.97,
      nominalPowerRpm: 7000,
      maxTorqueNm: 2.2,
      maxTorqueRpm: 5000,
      airFilterType: 'Semi-seco',
      fuelTankCapacityL: 0.63,
      fuelConsumptionLh: 0.69,
      fuelType: 'Gasolina de 90 oct',
      recommendedOil: 'SAE 10W-30 API - HONDA',
      dimensions: {
        length: 199,
        width: 260,
        height: 263,
      },
      weightKg: 4.13,
      accessories: [],
      warranty: '1 Año',
      strokeDiameterMm: '43 x 33',
      compressionRatio: '8:1',
      shaftType: 'Horizontal recto',
      coolingSystem: 'Aire Forzado',
      ignitionSystem: 'Magneto transistorizado',
      ignitionTime: 'B.T.D.C. 30°',
      sparkPlugs: 'CMR5H (NGK)',
      lubricationSystem: 'Salpicadura',
      startSystem: 'A cuerda retráctil',
      stopSystem: 'Circuito primario, ignición a tierra',
      oilCapacityCc: 130,
      oilAlertSystem: null, // No especificado
      additionalFeatures: null, // No especificados
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motor GX630RH',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'GX630RH',
    category: 'Motor',
    specs: {
      engineType: '4 tiempos V-TWIN',
      valveSystem: 'OHV',
      displacementCc: 688,
      maxPowerHp: 23,
      maxPowerRpm: 3600,
      nominalPowerHp: 20.8,
      nominalPowerRpm: 3600,
      maxTorqueNm: 48.3,
      maxTorqueRpm: 2500,
      airFilterType: 'Dual',
      fuelTankCapacityL: null, // No especificado
      fuelConsumptionLh: 6,
      fuelType: 'Gasolina de 90',
      recommendedOil: 'SAE 10W-30 API - HONDA',
      dimensions: {
        length: 405,
        width: 410,
        height: 438,
      },
      weightKg: 44.4,
      accessories: [],
      warranty: '2 Años',
      strokeDiameterMm: '78 x 72',
      compressionRatio: '9.3 : 1',
      shaftType: 'Horizontal recto',
      coolingSystem: 'Aire Forzado',
      ignitionSystem: 'CDI',
      ignitionTime: 'B.T.D.C. 9°',
      sparkPlugs: 'ZFR5F (NGK)',
      lubricationSystem: 'Alimentación forzada (bomba)',
      startSystem: 'Arranque eléctrico',
      stopSystem: 'Circuito primario, ignición a tierra',
      oilCapacityCc: 1700,
      oilAlertSystem: 'No',
      additionalFeatures: null, // No especificados
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motor GXR120RT',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'GXR120RT',
    category: 'Motor',
    specs: {
      engineType: '4 tiempos monocilíndrico',
      valveSystem: 'OHC',
      displacementCc: 121,
      maxPowerHp: 4,
      maxPowerRpm: 3600,
      nominalPowerHp: 3.6,
      nominalPowerRpm: 3600,
      maxTorqueNm: 7.5,
      maxTorqueRpm: 2500,
      airFilterType: 'Seco',
      fuelTankCapacityL: null, // No especificado
      fuelConsumptionLh: 1.0,
      fuelType: 'Gasolina de 90 oct',
      recommendedOil: 'SAE 10W-30 API - HONDA',
      dimensions: {
        length: 259,
        width: 294,
        height: 290,
      },
      weightKg: 10.4,
      accessories: [],
      warranty: null, // No especificado
      strokeDiameterMm: '60 x 42',
      compressionRatio: '8.5:1',
      shaftType: 'Horizontal cónico',
      coolingSystem: 'Aire Forzado',
      ignitionSystem: 'Magneto transistorizado',
      ignitionTime: 'B.T.D.C. 25°',
      sparkPlugs: 'CR5HSB (NGK)/U16FSR-UB (DENSO)',
      lubricationSystem: 'Salpicadura',
      startSystem: 'A cuerda retráctil',
      stopSystem: 'Circuito primario, ignición a tierra',
      oilCapacityCc: 280,
      oilAlertSystem: 'Sí',
      additionalFeatures: null, // No especificados
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motor GXV160H2 (HRJ216K3 TWNH)',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'GXV160H2',
    category: 'Motor',
    specs: {
      engineType: '4 tiempos, válvulas en cabeza, monocilíndrico',
      displacementCc: 163,
      strokeDiameterMm: '68.0 x 45.0 mm',
      continuousNominalPowerKw: 2.0,
      continuousNominalPowerRpm: 3000,
      netPowerKw: 2.7,
      netPowerRpm: 3000,
      maxNetTorqueNm: 9.0,
      maxNetTorqueRpm: 2500,
      compressionRatio: '8.0 ± 0.2',
      coolingSystem: 'Aire forzado',
      ignitionSystem: 'Magneto transistorizado',
      carburetorType: 'Válvula de mariposa tipo horizontal',
      airFilterType: 'Tipo dual',
      lubricationSystem: 'Salpicadura forzada',
      oilTankCapacityL: 0.65,
      startSystem: 'Arrancador de retorceso',
      recommendedFuel: 'Gasolina sin plomo superior a 86 oct',
      fuelTankCapacityL: 1.5,
      cuttingWidthCm: 53,
      cuttingHeightLevels: '11 niveles [1.6 cm - 7.6 cm (0.6 - 3.0 in)]',
      wheelDiameterMm: 200,
      bladeThicknessMm: 2.0,
      elevationMm: 26,
      speedFirstGearMs: 0.8,
      speedSecondGearMs: 1.1,
      speedThirdGearMs: 1.4,
      transmissionOil: 'Aceite para engranajes hipoides SAE #90',
      transmissionOilCapacityL: 0.2,
      dischargeMode: 'Descarga posterior / bolsa',
      collectorBagCapacityL: 70,
      dimensions: {
        totalLengthM: 1.74,
        totalWidthM: 0.57,
        totalHeightM: 1.15,
      },
      dryWeightKg: 49,
      operatingWeightKg: 51,
      frontWheelBandMm: 470,
      rearWheelBandMm: 500,
      rearWheelBandMm2: 625,
      wheelBaseMm: null, // No especificado
      accessories: [],
      warranty: null, // No especificado
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motor GX390T2',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'GX390T2',
    category: 'Motor',
    specs: {
      engineType: '4 tiempos monocilíndrico',
      valveSystem: 'OHV',
      displacementCc: 389,
      maxPowerHp: 16,
      maxPowerRpm: 4000,
      nominalPowerHp: 15.2,
      nominalPowerRpm: 4000,
      maxNetTorqueNm: 28.5,
      maxNetTorqueRpm: 3000,
      airFilterType: 'Especial para bote, tipo parrilla',
      fuelTankCapacityL: 6.1,
      fuelConsumptionLHr: 5.4,
      recommendedFuel: 'Gasolina de 90 oct',
      oilType: 'SAE 10W-30 API - HONDA',
      dimensions: {
        lengthMm: 405,
        widthMm: 462,
        heightMm: 437,
      },
      dryWeightKg: 29.1,
      accessoriesIncluded: [],
      warranty: null, // No especificado
      strokeDiameterMm: '88 x 64',
      compressionRatio: '8.2 : 1',
      axleType: 'Horizontal recto',
      coolingSystem: 'Aire Forzado',
      ignitionSystem: 'CDI',
      ignitionTiming: 'B.T.D.C. 8°',
      sparkPlugs: 'BP6ES (NGK)',
      lubricationSystem: 'Salpicadura',
      startSystem: 'A cuerda retráctil',
      stopSystem: 'Circuito primario, ignición a tierra',
      oilCapacityCc: 1100,
      oilAlertSystem: 'No',
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },

  {
    title: 'Motor GX35T',
    brand: 'Honda',
    imageUrl: imgHonda[Math.round(Math.random() * (imgHonda.length - 1))],
    model: 'GX35T',
    category: 'Motor',
    specs: {
      engineType: 'Monocilíndrico',
      valveSystem: '4T - OHC',
      maxPowerHp: 1.6,
      maxPowerRpm: 7000,
      fuelTankCapacityL: 0.63,
      oilTankCapacityC: 100,
      nominalDiameterMm: 7.5,
      dimensions: {
        lengthMm: 400,
        widthMm: 415,
        heightMm: 695,
      },
      dryWeightKg: 12.5,
      operatingWeightKg: 13.2, // incluyendo aceite de la bomba
      maximumFlowRateLMin: 8, // caudal máximo de salida
      chemicalTankCapacityL: 25, // capacidad del tanque del químico
      oilTankCapacityCc: 120, // capacidad del tanque de aceite
      accessories: [
        '1 lanza larga distancia de una salida',
        '1 llave sacabujías',
        '1 llave allen hexagonal 4mm',
      ],
      pumpSpecifications: {
        maxSprayPressureBar: 1, // presión/pulverización máxima
      },
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },
  {
    title: 'Motor Gasolinero RATO R100',
    brand: 'RATO',
    imageUrl: imgRato[Math.round(Math.random() * (imgRato.length - 1))],
    model: 'R100',
    category: 'Motor Gasolinero',
    specs: {
      applications: [
        'Agricultura',
        'Jardinería',
        'Construcción',
        'Minería',
        'Pesca',
        'Limpieza',
        'Esparcimiento',
        'Mini cultivador',
        'Hidrolavadoras',
        'Generador',
      ],
      engineType: 'Motor de 4 tiempos, OHV, Monocilíndrico',
      maxPowerHp: 3.0,
      ratedPowerHp: 2.7,
      ratedRpm: 3600,
      maxTorqueNm: 5.2,
      torqueRpm: 2500,
      displacementCc: 98,
      bore: 56,
      stroke: 40,
      compressionRatio: '8.5:1',
      ignitionSystem: 'Encendido magnético transistorizado',
      starter: 'A cuerda Retráctil',
      carburetor: 'De flotador o boya (De válvula de aspiración plana)',
      lubricationSystem: 'Salpicadura forzada',
      oilAlert: true,
      fuelType: 'Gasolina regular',
      oilType: 'SAE 10W-30',
      airFilter: 'Esponja',
      fuelTankCapacityL: 1.8,
      oilCapacityL: 0.35,
      mufflerProtection: true,
      consumption: '≤ 450 g/kW·h',
      weightKg: 10,
      dimensionsMm: '310 x 290 x 310',
      manufacturer: 'CHONGQING RATO TECHNOLOGY CORPORATION',
      origin: 'China',
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },
  {
    title: 'Motor Gasolinero RATO R100',
    brand: 'RATO',
    imageUrl: imgRato[Math.round(Math.random() * (imgRato.length - 1))],
    model: 'R100',
    category: 'Motor Gasolinero',
    specs: {
      applications: [
        'Agricultura',
        'Jardinería',
        'Construcción',
        'Minería',
        'Pesca',
        'Limpieza',
        'Esparcimiento',
        'Mini cultivador',
        'Hidrolavadoras',
        'Generador',
      ],
      engineType: 'Motor de 4 tiempos, OHV, Monocilíndrico',
      maxPowerHp: 3.0,
      ratedPowerHp: 2.7,
      ratedRpm: 3600,
      maxTorqueNm: 5.2,
      torqueRpm: 2500,
      displacementCc: 98,
      bore: 56,
      stroke: 40,
      compressionRatio: '8.5:1',
      ignitionSystem: 'Encendido magnético transistorizado',
      starter: 'A cuerda Retráctil',
      carburetor: 'De flotador o boya (De válvula de aspiración plana)',
      lubricationSystem: 'Salpicadura forzada',
      oilAlert: true,
      fuelType: 'Gasolina regular',
      oilType: 'SAE 10W-30',
      airFilter: 'Esponja',
      fuelTankCapacityL: 1.8,
      oilCapacityL: 0.35,
      mufflerProtection: true,
      consumption: '≤ 450 g/kW·h',
      weightKg: 10,
      dimensionsMm: '310 x 290 x 310',
      manufacturer: 'CHONGQING RATO TECHNOLOGY CORPORATION',
      origin: 'China',
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },
  {
    title: 'Motor Gasolinero RATO R100',
    brand: 'RATO',
    imageUrl: imgRato[Math.round(Math.random() * (imgRato.length - 1))],
    model: 'R100',
    category: 'Motor Gasolinero',
    specs: {
      applications: [
        'Agricultura',
        'Jardinería',
        'Construcción',
        'Minería',
        'Pesca',
        'Limpieza',
        'Esparcimiento',
        'Mini cultivador',
        'Hidrolavadoras',
        'Generador',
      ],
      engineType: 'Motor de 4 tiempos, OHV, Monocilíndrico',
      maxPowerHp: 3.0,
      ratedPowerHp: 2.7,
      ratedRpm: 3600,
      maxTorqueNm: 5.2,
      torqueRpm: 2500,
      displacementCc: 98,
      bore: 56,
      stroke: 40,
      compressionRatio: '8.5:1',
      ignitionSystem: 'Encendido magnético transistorizado',
      starter: 'A cuerda Retráctil',
      carburetor: 'De flotador o boya (De válvula de aspiración plana)',
      lubricationSystem: 'Salpicadura forzada',
      oilAlert: true,
      fuelType: 'Gasolina regular',
      oilType: 'SAE 10W-30',
      airFilter: 'Esponja',
      fuelTankCapacityL: 1.8,
      oilCapacityL: 0.35,
      mufflerProtection: true,
      consumption: '≤ 450 g/kW·h',
      weightKg: 10,
      dimensionsMm: '310 x 290 x 310',
      manufacturer: 'CHONGQING RATO TECHNOLOGY CORPORATION',
      origin: 'China',
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },
  {
    title: 'Generador Gasolinero RATO R12000DP-A',
    brand: 'RATO',
    imageUrl: imgRato[Math.round(Math.random() * (imgRato.length - 1))],
    model: 'R12000DP-A',
    category: 'Generador Gasolinero',
    specs: {
      applications: [
        'Industria',
        'Hogar',
        'Recreos',
        'Esparcimiento',
        'Puestos móviles de venta',
      ],
      engineType: 'Generador a gasolina, monofásico, OHV',
      maxPowerW: 12000,
      ratedPowerW: 11000,
      voltage: '220 V',
      frequencyHz: 60,
      dcOutput: '12 V / 8.3 A',
      runtimeFullLoadH: 4,
      runtimeHalfLoadH: 7,
      noiseLevelDb: 85,
      displacementCc: 669,
      engineConfig: 'En V',
      bore: 78,
      stroke: 70,
      compressionRatio: '8.5:1',
      fuelTankCapacityL: 30,
      starter: 'Arranque eléctrico',
      weightKg: 150,
      dimensionsMm: '820 x 595 x 685',
      certifications: [
        'CSA',
        'ISO 9001:2008',
        'GB/T 19001:2008',
        'ISO 14001:2004',
        'GB/T 24001:2014',
      ],
      manufacturer: 'CHONGQING RATO TECHNOLOGY CORPORATION',
      origin: 'China',
      features: [
        'Cámara de combustión esférica de alto rendimiento',
        'Doble barra de protección del tanque',
        'Tanque de gran capacidad para operación prolongada',
        'Silenciador de gran capacidad para reducir ruido y emisiones',
        'Modo de inicio con una sola pulsación',
        'Alternador con bobinado de cobre completo',
        'Alerta de bajo nivel de combustible',
        'Alerta de bajo nivel de aceite',
        'VFT disponible',
        'Ajuste automático de voltaje (AVR)',
        'Panel de control versátil',
        'Bajas emisiones, baja vibración y bajo ruido',
        'Fácil mantenimiento',
      ],
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },
  {
    title: 'Motor Gasolinero RATO R210',
    brand: 'RATO',
    imageUrl: imgRato[Math.round(Math.random() * (imgRato.length - 1))],
    model: 'R210',
    category: 'Motor Gasolinero',
    specs: {
      applications: [
        'Agricultura',
        'Jardinería',
        'Construcción',
        'Minería',
        'Pesca',
        'Limpieza',
        'Esparcimiento',
      ],
      engineType: 'Motor de 4 tiempos, OHV, Monocilíndrico',
      maxPowerHp: 7.0,
      ratedPowerHp: 6.44,
      ratedRpm: 3600,
      displacementCc: 212,
      bore: 70,
      stroke: 55,
      compressionRatio: '9.0:1',
      maxTorqueNm: 12,
      torqueRpm: 2500,
      ignitionSystem: 'Encendido magnético transistorizado',
      starter: 'A cuerda Retráctil',
      carburetor: 'De flotador o boya (De válvula de aspiración plana)',
      lubricationSystem: 'Salpicadura forzada',
      governorSystem: 'Mecánico centrífugo',
      oilAlert: true,
      fuelType: 'Gasolina de 90 oct.',
      oilType: 'Multigrado SAE 20W-50',
      airFilter: 'Elemento dual (papel & esponja)',
      fuelTankCapacityL: 3.6,
      oilCapacityL: 0.55,
      mufflerProtection: true,
      shaftDiameterMm: 19.05,
      consumption: '≤ 395 g/kW·h',
      weightKg: 16,
      dimensionsMm: '390 x 320 x 345',
      emissionsCertification: 'EPA',
      manufacturer: 'CHONGQING RATO TECHNOLOGY CORPORATION',
      origin: 'China',
      features: [
        'Camisa de cilindro de hierro fundido',
        'Doble rodamiento de bolas',
        'Cigüeñal de acero forjado y templado',
        'Liberación automática de la compresión',
        'Sistema automático de parada del motor por bajo nivel de aceite',
        'Nuevo balancín estructurado',
        'Optimización de entrada/salida de gases',
        'Cámara de combustión modificada para mayor potencia y menor consumo',
      ],
    },
    stock: {
      Piura: Math.floor(Math.random() * 100),
      Sullana: Math.floor(Math.random() * 100),
      Tambogrande: Math.floor(Math.random() * 100),
    },
  },
  {
    title: 'Motor Gasolinero RATO R210-V',
    brand: 'RATO',
    imageUrl: imgRato[Math.round(Math.random() * (imgRato.length - 1))],
    model: 'R210-V',
    category: 'Motor Gasolinero',
    specs: {
      applications: ['Embarcaciones fluviales', 'Peque-peque'],
      engineType: 'Motor de peque-peque, 4 tiempos, OHV, Monocilíndrico',
      displacementCc: 212,
      bore: 70,
      stroke: 55,
      ratedPowerHp: 7.5,
      ratedRpm: 3600,
      maxTorqueNm: 14.5,
      torqueRpm: 2500,
      compressionRatio: '9.0:1',
      powerTakeoff: 'Salida del eje horizontal',
      ignitionSystem: 'Encendido magnético transistorizado',
      starter: 'A cuerda Retráctil',
      carburetor: 'De flotador o boya (De válvula de aspiración plana)',
      lubricationSystem: 'Salpicadura forzada',
      governorSystem: 'Mecánico centrífugo',
      oilCapacityL: 0.55,
      fuelTankCapacityL: 3.6,
      consumption: '≤ 395 g/kW·h',
      weightKg: 15.5,
      dimensionsMm: '390 x 320 x 345',
      emissionsCertification: 'EPA',
      manufacturer: 'CHONGQING RATO TECHNOLOGY CORPORATION',
      origin: 'China',
      features: [
        'Superficies con recubrimiento de cromo contra oxidación',
        'Camisa de cilindro de hierro fundido',
        'Doble rodamiento de bolas',
        'Cigüeñal de acero forjado y templado',
        'Liberación automática de la compresión',
        'Parada automática por bajo nivel de aceite',
        'Balancín estructurado de larga vida útil',
        'Optimización de flujo de aire de admisión y escape',
        'Cámara de combustión modificada para mayor potencia y menor consumo',
      ],
    },
    stock: {
      Piura: 63,
      Sullana: 17,
      Tambogrande: 42,
    },
  },
  {
    title: 'Motor Gasolinero RATO R300',
    brand: 'RATO',
    imageUrl: imgRato[Math.round(Math.random() * (imgRato.length - 1))],
    model: 'R300',
    category: 'Motor Gasolinero',
    specs: {
      applications: [
        'Agricultura',
        'Jardinería',
        'Construcción',
        'Minería',
        'Pesca',
        'Limpieza',
        'Esparcimiento',
      ],
      engineType: 'Motor de 4 tiempos, OHV, Monocilíndrico',
      maxPowerHp: 10,
      ratedPowerHp: 8.8,
      ratedRpm: 3600,
      displacementCc: 301,
      bore: 80,
      stroke: 60,
      compressionRatio: '8.5:1',
      maxTorqueNm: 18,
      torqueRpm: 2500,
      ignitionSystem: 'Encendido magnético transistorizado',
      starter: 'A cuerda Retráctil',
      carburetor: 'De flotador o boya (De válvula de aspiración plana)',
      lubricationSystem: 'Salpicadura forzada',
      governorSystem: 'Mecánico centrífugo',
      oilAlert: true,
      fuelType: 'Gasolina de 90 oct.',
      oilType: 'Multigrado SAE 20W-50',
      airFilter: 'Elemento dual (papel & esponja)',
      fuelTankCapacityL: 5.4,
      oilCapacityL: 1.1,
      mufflerProtection: true,
      shaftDiameterMm: 25.4,
      consumption: '≤ 374 g/kW·h',
      weightKg: 30.5,
      dimensionsMm: '420 x 395 x 430',
      emissionsCertification: 'EPA',
      manufacturer: 'CHONGQING RATO TECHNOLOGY CORPORATION',
      origin: 'China',
      features: [
        'Camisa de cilindro de hierro fundido',
        'Doble rodamiento de bolas',
        'Cigüeñal de acero forjado y templado',
        'Liberación automática de la compresión',
        'Parada automática por bajo nivel de aceite',
        'Nuevo balancín estructurado para mayor estabilidad y vida útil',
        'Optimización de entrada y salida de gases',
        'Cámara de combustión modificada para mayor potencia y menor consumo',
      ],
    },
    stock: {
      Piura: 51,
      Sullana: 89,
      Tambogrande: 33,
    },
  },
  {
    title: 'Motor Gasolinero RATO R300',
    brand: 'RATO',
    imageUrl: imgRato[Math.round(Math.random() * (imgRato.length - 1))],
    model: 'R300',
    category: 'Motor Gasolinero',
    specs: {
      applications: [
        'Agricultura',
        'Jardinería',
        'Construcción',
        'Minería',
        'Pesca',
        'Limpieza',
        'Esparcimiento',
      ],
      engineType: 'Motor de 4 tiempos, OHV, Monocilíndrico',
      maxPowerHp: 10,
      ratedPowerHp: 8.8,
      ratedRpm: 3600,
      displacementCc: 301,
      bore: 80,
      stroke: 60,
      compressionRatio: '8.5:1',
      maxTorqueNm: 18,
      torqueRpm: 2500,
      ignitionSystem: 'Encendido magnético transistorizado',
      starter: 'A cuerda Retráctil',
      carburetor: 'De flotador o boya (De válvula de aspiración plana)',
      lubricationSystem: 'Salpicadura forzada',
      governorSystem: 'Mecánico centrífugo',
      oilAlert: true,
      fuelType: 'Gasolina de 90 oct.',
      oilType: 'Multigrado SAE 20W-50',
      airFilter: 'Elemento dual (papel & esponja)',
      fuelTankCapacityL: 5.4,
      oilCapacityL: 1.1,
      mufflerProtection: true,
      shaftDiameterMm: 25.4,
      consumption: '≤ 374 g/kW·h',
      weightKg: 30.5,
      dimensionsMm: '420 x 395 x 430',
      emissionsCertification: 'EPA',
      manufacturer: 'CHONGQING RATO TECHNOLOGY CORPORATION',
      origin: 'China',
      features: [
        'Camisa de cilindro de hierro fundido',
        'Doble rodamiento de bolas',
        'Cigüeñal de acero forjado y templado',
        'Liberación automática de la compresión',
        'Parada automática por bajo nivel de aceite',
        'Nuevo balancín estructurado para mayor estabilidad y vida útil',
        'Optimización de entrada y salida de gases',
        'Cámara de combustión modificada para mayor potencia y menor consumo',
      ],
    },
    stock: {
      Piura: 28,
      Sullana: 72,
      Tambogrande: 11,
    },
  },
  {
    title: 'Motor Gasolinero RATO R300',
    brand: 'RATO',
    imageUrl: imgRato[Math.round(Math.random() * (imgRato.length - 1))],
    model: 'R300',
    category: 'Motor Gasolinero',
    specs: {
      applications: [
        'Agricultura',
        'Jardinería',
        'Construcción',
        'Minería',
        'Pesca',
        'Limpieza',
        'Esparcimiento',
      ],
      engineType: 'Motor de 4 tiempos, OHV, Monocilíndrico',
      maxPowerHp: 10,
      ratedPowerHp: 8.8,
      ratedRpm: 3600,
      displacementCc: 301,
      bore: 80,
      stroke: 60,
      compressionRatio: '8.5:1',
      maxTorqueNm: 18,
      torqueRpm: 2500,
      ignitionSystem: 'Encendido magnético transistorizado',
      starter: 'A cuerda Retráctil',
      carburetor: 'De flotador o boya (De válvula de aspiración plana)',
      lubricationSystem: 'Salpicadura forzada',
      governorSystem: 'Mecánico centrífugo',
      oilAlert: true,
      fuelType: 'Gasolina de 90 oct.',
      oilType: 'Multigrado SAE 20W-50',
      airFilter: 'Elemento dual (papel & esponja)',
      fuelTankCapacityL: 5.4,
      oilCapacityL: 1.1,
      mufflerProtection: true,
      shaftDiameterMm: 25.4,
      consumption: '≤ 374 g/kW·h',
      weightKg: 30.5,
      dimensionsMm: '420 x 395 x 430',
      emissionsCertification: 'EPA',
      manufacturer: 'CHONGQING RATO TECHNOLOGY CORPORATION',
      origin: 'China',
      features: [
        'Camisa de cilindro de hierro fundido',
        'Doble rodamiento de bolas',
        'Cigüeñal de acero forjado y templado',
        'Liberación automática de la compresión',
        'Parada automática por bajo nivel de aceite',
        'Nuevo balancín estructurado para mayor estabilidad y vida útil',
        'Optimización de entrada y salida de gases',
        'Cámara de combustión modificada para mayor potencia y menor consumo',
      ],
    },
    stock: {
      Piura: 64,
      Sullana: 47,
      Tambogrande: 22,
    },
  },
  {
    title: 'Motor Gasolinero RATO RM120-V',
    brand: 'RATO',
    imageUrl: imgRato[Math.round(Math.random() * (imgRato.length - 1))],
    model: 'RM120-V',
    category: 'Motor Gasolinero',
    specs: {
      applications: ['Apisonadores'],
      engineType: 'Motor de 4 tiempos, OHV, monocilíndrico',
      displacementCc: 121,
      bore: 60,
      stroke: 43,
      ratedPowerHp: 3.6,
      ratedRpm: 3600,
      maxTorqueNm: 7.5,
      torqueRpm: 2500,
      starter: 'A cuerda Retráctil',
      fuelType: 'Gasolina regular',
      oilType: 'SAE 10W-30',
      lubricationSystem: 'Salpicadura forzada',
      airFilter: 'Filtro de papel',
      oilCapacityL: 0.35,
      fuelConsumptionLph: 1.0,
      weightKg: 11.5,
      dimensionsMm: '259 x 294 x 290',
      emissionsCertification: ['EPA3', 'EU'],
      recommendedRpm: '3600 ~ 4000',
      manufacturer: 'CHONGQING RATO TECHNOLOGY CORPORATION',
      origin: 'China',
      features: [
        'Diseñado exclusivamente para apisonadores',
        'Peso neto 25% menor que competidores',
        'Relación peso-potencia 40% superior',
        'Árbol de levas central para mejor equilibrio dinámico',
        'Culata dividida y cámara de combustión esférica',
        'Cumple con normas EPA3',
        'Cilindro y pistón con tratamiento especial de dureza',
        'Dispositivo de límite de velocidad para seguridad del usuario',
        'Optimiza el suministro de combustible en cualquier inclinación',
      ],
    },
    stock: {
      Piura: 28,
      Sullana: 45,
      Tambogrande: 18,
    },
  },
  {
    title: 'Motor Gasolinero RATO RM120-V',
    brand: 'RATO',
    imageUrl: imgRato[Math.round(Math.random() * (imgRato.length - 1))],
    model: 'RM120-V',
    category: 'Motor Gasolinero',
    specs: {
      applications: ['Apisonadores'],
      engineType: 'Motor de 4 tiempos, OHV, monocilíndrico',
      displacementCc: 121,
      bore: 60,
      stroke: 43,
      ratedPowerHp: 3.6,
      ratedRpm: 3600,
      maxTorqueNm: 7.5,
      torqueRpm: 2500,
      starter: 'A cuerda Retráctil',
      fuelType: 'Gasolina regular',
      oilType: 'SAE 10W-30',
      lubricationSystem: 'Salpicadura forzada',
      airFilter: 'Filtro de papel',
      oilCapacityL: 0.35,
      fuelConsumptionLph: 1.0,
      weightKg: 11.5,
      dimensionsMm: '259 x 294 x 290',
      emissionsCertification: ['EPA3', 'EU'],
      recommendedRpm: '3600 ~ 4000',
      manufacturer: 'CHONGQING RATO TECHNOLOGY CORPORATION',
      origin: 'China',
      features: [
        'Diseño exclusivo para apisonadores con derechos de propiedad intelectual',
        '25% más ligero que los competidores',
        'Relación peso-potencia 40% superior',
        'Árbol de levas central para equilibrio dinámico óptimo',
        'Cámara de combustión esférica y culata dividida',
        'Emisiones optimizadas y certificación EPA3',
        'Cilindro, pistón y anillos con tratamiento de resistencia al desgaste',
        'Limitador de velocidad para seguridad del usuario',
        'Sistema de combustible adaptado a múltiples inclinaciones',
      ],
    },
    stock: {
      Piura: 38,
      Sullana: 60,
      Tambogrande: 25,
    },
  },
  {
    title: 'Motor Gasolinero RATO RM120-V',
    brand: 'RATO',
    imageUrl: imgRato[Math.round(Math.random() * (imgRato.length - 1))],
    model: 'RM120-V',
    category: 'Motor Gasolinero',
    specs: {
      applications: ['Apisonadores'],
      engineType: 'Motor de 4 tiempos, OHV, monocilíndrico',
      displacementCc: 121,
      bore: 60,
      stroke: 43,
      ratedPowerHp: 3.6,
      ratedRpm: 3600,
      maxTorqueNm: 7.5,
      torqueRpm: 2500,
      starter: 'A cuerda Retráctil',
      fuelType: 'Gasolina regular',
      oilType: 'SAE 10W-30',
      lubricationSystem: 'Salpicadura forzada',
      airFilter: 'Filtro de papel',
      oilCapacityL: 0.35,
      fuelConsumptionLph: 1.0,
      weightKg: 11.5,
      dimensionsMm: '259 x 294 x 290',
      emissionsCertification: ['EPA3', 'EU'],
      recommendedRpm: '3600 ~ 4000',
      manufacturer: 'CHONGQING RATO TECHNOLOGY CORPORATION',
      origin: 'China',
      features: [
        'Diseñado exclusivamente para uso en apisonadores',
        'Desarrollado por RATO CHONGQING con propiedad intelectual propia',
        '25% más ligero que competidores principales',
        '40% mayor relación peso-potencia',
        'Árbol de levas central para equilibrio dinámico',
        'Culata dividida y cámara de combustión esférica',
        'Emisiones optimizadas que cumplen con EPA3',
        'Cilindro, pistón y anillos con tratamiento de resistencia al desgaste',
        'Limitador de velocidad para seguridad del usuario',
        'Sistema de alimentación resistente a múltiples ángulos de inclinación',
      ],
    },
    stock: {
      Piura: 45,
      Sullana: 32,
      Tambogrande: 17,
    },
  },
  {
    title: 'Motor Gasolinero RATO RM120-V',
    brand: 'RATO',
    imageUrl: imgRato[Math.round(Math.random() * (imgRato.length - 1))],
    model: 'RM120-V',
    category: 'Motor Gasolinero',
    specs: {
      applications: ['Apisonadores'],
      engineType: 'Motor de 4 tiempos, OHV, monocilíndrico',
      displacementCc: 121,
      bore: 60,
      stroke: 43,
      ratedPowerHp: 3.6,
      ratedRpm: 3600,
      maxTorqueNm: 7.5,
      torqueRpm: 2500,
      starter: 'A cuerda Retráctil',
      fuelType: 'Gasolina regular',
      oilType: 'SAE 10W-30',
      lubricationSystem: 'Salpicadura forzada',
      airFilter: 'Filtro de papel',
      oilCapacityL: 0.35,
      fuelConsumptionLph: 1.0,
      weightKg: 11.5,
      dimensionsMm: '259 x 294 x 290',
      emissionsCertification: ['EPA3', 'EU'],
      recommendedRpm: '3600 ~ 4000',
      manufacturer: 'CHONGQING RATO TECHNOLOGY CORPORATION',
      origin: 'China',
      features: [
        'Diseñado exclusivamente para uso en apisonadores',
        'Desarrollado por RATO CHONGQING con propiedad intelectual propia',
        '25% más ligero que competidores principales',
        '40% mayor relación peso-potencia',
        'Árbol de levas central para equilibrio dinámico',
        'Culata dividida y cámara de combustión esférica',
        'Optimización de emisiones según normas EPA3',
        'Tratamiento especial de cilindro, pistón y anillos',
        'Limitador de velocidad para mayor seguridad',
        'Sistema de combustible adaptado a inclinaciones múltiples',
      ],
    },
    stock: {
      Piura: 23,
      Sullana: 54,
      Tambogrande: 15,
    },
  },
  {
    title: 'Cortacésped Autopropulsado RATO RMS53Q-V225',
    brand: 'RATO',
    imageUrl: imgRato[Math.round(Math.random() * (imgRato.length - 1))],
    model: 'RMS53Q-V225',
    category: 'Cortacésped',
    specs: {
      applications: ['Jardines', 'Parques', 'Campos deportivos'],
      cuttingWidthCm: 53,
      deckMaterial: 'Acero',
      engineModel: 'RV225-S2',
      engineDisplacementCc: 223,
      maxPowerHp: 7.5,
      sideDischarge: true,
      mulchingKit: true,
      rearDischarge: true,
      rearBag: true,
      bagMaterial: 'Tejido',
      bagVolumeL: 65,
      cuttingHeightRangeCm: '3.0 - 9.5',
      heightAdjustment: 'Palanca lateral (rueda trasera)',
      heightPositions: 7,
      frontWheelSizeCm: 20,
      rearWheelSizeCm: 25,
      driveSystem: 'Tracción trasera',
      netWeightKg: 30.5,
      dimensionsMm: '920 × 595 × 430',
      features: [
        'Fácil manejo y control: agarradera con recubrimiento de espuma',
        'Palanca de freno del motor y palanca de embrague',
        'Marco ajustable en dos posiciones y plegable para almacenamiento',
        'Parachoque delantero de fácil uso',
        'Arranque fácil, confiable y duradero',
        'Cumple con las normas EPA, CARB, EU5 y CE',
        '3 funciones en 1: ensacado trasero, descarga lateral, mulching',
      ],
      manufacturer: 'CHONGQING RATO TECHNOLOGY CORPORATION',
      origin: 'China',
    },
    stock: {
      Piura: 17,
      Sullana: 39,
      Tambogrande: 26,
    },
  },
];
