import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  // Crear usuarios
  // await prisma.user.create({
  //   data: {
  //     name: '',
  //     email: '',
  //     password: '',
  //     role: 'ADMIN',
  //   },
  // });

  // await prisma.user.create({
  //   data: {
  //     name: '',
  //     email: '',
  //     password: '',
  //   },
  // });

  // Crear productos
  await prisma.product.createMany({
    data: [
      {
        title: 'Atomizador de Mochila Cifarelli L3EVO18',
        brand: 'Cifarelli',
        model: 'L3EVO18',
        category: 'Atomizador',
        specs: {
          applications: [
            'Control de plagas en hortalizas y frutales',
            'Control de vectores y demás aplicaciones de Sanidad Pública',
          ],
          engineType:
            'CIFARELLI C7 monocilíndrico de 2 tiempos refrigerado por aire',
          displacementCc: 77,
          bore: 52,
          stroke: 36,
          maxPowerHp: 5,
          powerKw: 3.6,
          carburetor: 'Carburador',
          ignitionSystem: 'Encendido electrónico',
          sparkPlug: 'CHAMPION RCJ6Y',
          fuelTankCapacityL: 1.9,
          fuelType: 'Mezcla de gasolina y aceite para 2 tiempos',
          liquidTankCapacityL: 18,
          liquidFlowRateLmin: 3.6,
          dropletSize: 'Ø 120 µm',
          maxHorizontalRangeM: 17,
          maxVerticalRangeM: 15,
          airVolumeM3h: 1200,
          airSpeedMps: 125,
          acceleration: '450 Km/h / 280 MPH',
          handleType: 'Empuñadura con gatillo de aceleración',
          noiseLevelLpfaDb: 98.7,
          noiseLevelLwaDb: 113.6,
          vibrationLevelMss: 3.5,
          weightWithoutTubeKg: 10.62,
          weightWithTubeKg: 11.36,
          packagingDimensionsCm: '49 x 74 x 38',
          accessories: [
            'Llave sacabujía con destornillador - cabeza hexagonal',
            'Abrazaderas Ø 67',
            'Botella para preparación mezcla de combustible',
            'Tobera (boquilla pulverizadora)',
            'Boca difusora',
            'Kit de rejillas (cod.: 0G34100)',
          ],
          manufacturer: 'CIFARELLI S.P.A. MADE IN ITALY',
          membraneRuixing: 'Graduada: 18 L / Máxima: 20 L',
        },
      },
      {
        title: 'Soplador de Mochila Cifarelli BL 1200',
        brand: 'Cifarelli',
        model: 'BL 1200',
        category: 'Soplador',
        specs: {
          applications: [
            'Limpieza de grandes áreas eliminando hojas, hierba u otro material',
            'Recolección de aceitunas y frutos con cáscara como castañas o avellanas',
            'En apicultura, se emplea para alejar a las abejas de las colmenas durante la extracción de miel',
          ],
          engineType:
            'CIFARELLI C7 monocilíndrico de 2 tiempos refrigerado por aire',
          displacementCc: 77,
          bore: 52,
          stroke: 36,
          maxPowerHp: 5,
          powerKw: 3.6,
          carburetor: 'WALBRO de membrana con cápsula',
          ignitionSystem: 'Encendido electrónico',
          sparkPlug: 'CHAMPION RCJ6Y',
          fuelTankCapacityL: 2.3,
          fuelType: 'Mezcla de gasolina y aceite para 2 tiempos',
          tubeType: 'Tubo telescópico',
          diffuserType: 'Difusores',
          airVolumeWithoutBlowerM3h: 1620,
          airVolumeWithBlowerM3h: 1092,
          airSpeedMps: 82.3,
          acceleration: '296 Km/h / 184 MPH (con dispositivo de soplado)',
          handleType: 'Empuñadura con gatillo de aceleración',
          noiseLevelLpfaMaxDb: 78,
          noiseLevelLpfaMinDb: 54.5,
          vibrationLevelMss: '< 2.5',
          weightWithoutBlowerKg: 10.13,
          weightWithBlowerKg: 11.32,
          packagingDimensionsCm: '64 x 46 x 36',
          noiseLevelLwaDb: 115,
          accessories: [
            'Llave sacabujía con destornillador - cabeza hexagonal',
            'Abrazaderas Ø 70',
            'Botella para preparación mezcla de combustible',
            'Tornillos TCEI M5x65',
          ],
          manufacturer: 'CIFARELLI S.P.A. MADE IN ITALY',
        },
      },
      {
        title: 'Espolvoreador Cifarelli M1200PG',
        brand: 'Cifarelli',
        model: 'M1200PG',
        category: 'Espolvoreador',
        specs: {
          applications: [
            'Tratamientos con productos en polvo (como azufre ventilado)',
            'Aplicación de gránulos y semillas de arroz (en la siembra)',
          ],
          engineType:
            'CIFARELLI C7 monocilíndrico de 2 tiempos refrigerado por aire',
          displacementCc: 77,
          bore: 52,
          stroke: 36,
          maxPowerHp: 5,
          powerKw: 3.6,
          carburetor: 'WALBRO de membrana con cápsula',
          ignitionSystem: 'Encendido electrónico',
          sparkPlug: 'CHAMPION RCJ6Y',
          fuelTankCapacityL: 2.3,
          fuelType: 'Mezcla de gasolina y aceite para 2 tiempos',
          tankCapacityL: 27,
          flowRegulationLevels: 5,
          calibratedCasings: 5,
          airVolumeM3h: 1620,
          airSpeedMps: 105,
          acceleration: '378 Km/h / 235 MPH',
          handleType: 'Empuñadura con gatillo de aceleración',
          noiseLevelLpfaDb: 103,
          noiseLevelLwaDb: 115,
          vibrationLevelMss: '< 2.5',
          weightWithoutTubeKg: 11.35,
          weightWithTubeKg: 12.2,
          packagingDimensionsCm: '96 x 46 x 47',
          accessories: [
            'Llave sacabujía con destornillador - cabeza hexagonal',
            'Abrazaderas Ø 90',
            'Botella para preparación mezcla de combustible',
            'Tornillos TCEI M5x65',
            'Cadena de seguridad (cadena de tierra)',
          ],
          manufacturer: 'CIFARELLI S.P.A. MADE IN ITALY',
        },
      },
      {
        title: 'Motobomba Ducati DCW35251',
        brand: 'Ducati',
        model: 'DCW35251',
        category: 'Motobomba',
        specs: {
          engineType:
            'Monocilíndrico 4T OHC Refrigerado por aire / Single cylinder, 4-stroke, OHC, Air cooled',
          displacementCc: 79,
          maxPowerKw: 1.87,
          maxPowerHp: 2.5,
          maxRpm: 3800,
          starterType: 'Manual',
          ignitionSystem: 'Magneto transitorizado / Transistorized magneto',
          suctionPortInches: 1,
          suctionPortMm: 25,
          dischargePortInches: 1,
          dischargePortMm: 25,
          totalLiftM: 30,
          suctionLiftM: 6,
          maxPumpingRateLh: 6000,
          selfPrimeTimeSec: 120,
          suctionDischargeFitting:
            '1"x25mm Aluminum fitting, aluminum fixing nut',
          suctionFilter: '25mm Polypropylene',
          lengthMm: 410,
          widthMm: 310,
          heightMm: 400,
          dryWeightKg: 13.5,
          fuelTankCapacityL: 1.6,
          fuelAutonomyMin: 110,
          accessories: [
            'Rácor en aluminio, Tuerca en aluminio',
            'Filtro de succión 25mm en Polipropileno',
          ],
          manufacturer: 'DUCATI Licensed',
        },
      },
      {
        title: 'Biotrituradora a Gasolina Ducati DWS65',
        brand: 'Ducati',
        model: 'DWS65',
        category: 'Biotrituradora',
        specs: {
          engineType: 'OHV (4T)',
          displacementCc: 196,
          maxPowerKw: 4.1,
          maxPowerHp: 6.5,
          primer: 'No',
          autoChoke: 'Sí',
          starterType: 'Manual / Recoil',
          ignitionSystem: 'Magneto transitorizado / Transistorized magneto',
          maxChippingDiameterInches: 4,
          maxChippingDiameterMm: 100,
          cuttingSystem: 'Trituración a rodillo / Drum shredding',
          numberOfBlades: 2,
          hopperFeedType: 'Manual',
          deflectingNozzleHeightM: 1.5,
          emergencyStop:
            'Sí, rodeando tolva de entrada / Yes, surrounding hopper mouth',
          transmission: 'Doble correa / Double belt',
          productivityM3h: '2.5 - 4',
          chassisMaterial: 'Acero / Steel',
          wheelDimensions: '4,10 / 3,5-4',
          fuelTankCapacityMl: 3600,
          soundLevelDbA: 98,
          netWeightKg: 95,
          grossWeightKg: 105,
          dimensionsMm: '870 x 890 x 565',
          containerCapacity: {
            twentyFoot: 48,
            fortyFoot: 'N/A',
            fortyHQ: 156,
          },
          eanCode: '8434691054912',
          additionalFeatures: [
            'Deflector de salida a 1,5m regulable en inclinación y orientable 360º',
            'Pie de apoyo más amplio para evitar el hundimiento en terreno blando',
            'Manillar de transporte de doble empuñadura',
            'Ruedas neumáticas grandes',
            'Ideal para troncos y material consistente',
            'Rotor de acero de gran durabilidad',
          ],
          manufacturer: 'DUCATI Licensed',
        },
      },
      {
        title: 'Biotrituradora a Gasolina Ducati DWS150-DWS150E',
        brand: 'Ducati',
        model: 'DWS150-DWS150E',
        category: 'Biotrituradora',
        specs: {
          engineType: 'OHV (4T)',
          displacementCc: 420,
          maxPowerKw: 11.25,
          maxPowerHp: 15.0,
          starterType: 'Manual (DWS 150) - Eléctrico (DWS 150E)',
          ignitionSystem: 'Magneto transitorizado / Transistorized magneto',
          maxChippingDiameterInches: 4.7,
          maxChippingDiameterMm: 120,
          cuttingSystem: 'Trituración a rodillo / Drum shredding',
          numberOfBlades: 2,
          hopperFeedType: 'Manual',
          deflectingNozzleHeightM: 1.5,
          emergencyStop:
            'Sí, rodeando tolva de entrada / Yes, surrounding hopper mouth',
          transmission: 'Doble correa / Double belt',
          productivityM3h: '5 - 8',
          chassisMaterial: 'Acero / Steel',
          wheelDimensions: '16*6.5-8',
          fuelTankCapacityL: 6.5,
          oilTankCapacityL: 1.1,
          recommendedOilType: 'SAE10W-30',
          soundLevelDbA: 98,
          netWeightKg: 190,
          grossWeightKg: 205,
          dimensionsMm: '895 x 765 x 1200',
          containerCapacity: {
            twentyFoot: 18,
            fortyFoot: 'N/A',
            fortyHQ: 78,
          },
          eanCode: '8434691109216 - 8434691309760',
          additionalFeatures: [
            'Deflector de salida a 1,5m regulable en inclinación y orientable 360º',
            'Pie de apoyo más amplio para evitar el hundimiento en terreno blando',
            'Manillar de transporte de doble empuñadura',
            'Ruedas neumáticas grandes',
            'Ideal para troncos y material consistente',
            'Rotor de acero de gran durabilidad',
          ],
          manufacturer: 'DUCATI Licensed',
        },
      },
      {
        title: 'Motor 4T OHV Monocilíndrico Ducati DPE270Q',
        brand: 'Ducati',
        model: 'DPE270Q',
        category: 'Motor',
        specs: {
          engineType: 'OHV 4T Monocilíndrico',
          displacementCc: 270,
          maxPowerHp: 9,
          netPowerKw: 5.4,
          netPowerHp: 7.2,
          bore: 77,
          stroke: 58,
          compressionRatio: '8.5 : 1',
          netTorqueNm: 18,
          governorSystem: 'Centrífuga mecánica / Mechanical',
          airFilter: 'Húmedo bañado en aceite / Oil Bath',
          oilTankCapacityL: 1.1,
          fuelTankCapacityL: 6,
          fuelConsumptionGkwH: 374,
          starterType: 'Manual / Recoil',
          dimensionsMm: '490 x 430 x 530',
          containerCapacity: {
            twentyFoot: 432,
            fortyFoot: 900,
            fortyHQ: 1050,
          },
          netWeightKg: 27,
          grossWeightKg: 30,
          eanCode: '8434691309845',
          easyStart: 'Sí / Yes',
          manufacturer: 'DUCATI Licensed',
        },
      },
      {
        title: 'Pulverizador Mochila DSP 2000',
        brand: 'Ducati',
        model: 'DSP3120S',
        category: 'Pulverizador',
        specs: {
          liquidTankCapacityL: 5.1,
          pistonTravelMm: 6.6,
          workingPressureBar: 2,
          workingPressureMpa: 0.2,
          netWeightKg: 20,
          grossWeightKg: 96,
          dimensionsMm: '410 x 210 x 570',
          containerCapacity: {
            twentyFoot: 360,
            fortyFoot: 1300,
            fortyHQ: 1500,
          },
          eanCode: '8434691037090',
          pumpType: 'Manual',
          manufacturer: 'DUCATI Licensed',
        },
      },
      {
        title: 'Motoazada Diesel DTL 11000D',
        brand: 'Ducati',
        model: 'DTL11000D',
        category: 'Motoazada Diesel',
        specs: {
          displacementCc: 418,
          maxPowerKw: 10,
          ratedPowerKw: 6.3,
          maxTorqueNm: 18.5,
          maxTorqueRpm: 2800,
          fuelTankCapacityL: 5.5,
          oilTankCapacityL: 1.65,
          airFilter: 'Oil Bath',
          engineDimensionsMm: '440 x 420 x 495',
          transmission: 'Gearbox',
          clutchType: 'Multidisc friction',
          gears: '4 + 2',
          workingWidthMm: '800 - 1000 - 1200 - 1500',
          handleType: 'Height regulation - Reversible',
          blades: 40,
          workingDepthMm: 320,
          security: 'Automatic stop',
          includedAccessories: [
            'Wheels 500 x 12mm',
            'Water pump',
            'PTO for extra accessories',
            'Fumigation pump',
            'Rear tine tiller',
            'Electric start',
            'Grass cutter',
            'Forage harvester',
            'Ditching machine',
          ],
          dimensionsMm: '1800 x 1150 x 1050',
          netWeightKg: 175,
          grossWeightKg: 190,
          containerCapacity: {
            twentyFoot: 40,
            fortyFoot: 88,
            fortyHQ: 1132,
          },
          eanCode: '8434691266735',
          manufacturer: 'DUCATI Licensed',
        },
      },
      {
        title: 'Motoazada Gasolina DTL 10000',
        brand: 'Ducati',
        model: 'DTL10000',
        category: 'Motoazada Gasolina',
        specs: {
          displacementCc: 212,
          maxPowerKw: 5.2,
          ratedPowerKw: 4.3,
          maxTorqueNm: 12.0,
          maxTorqueRpm: 2800,
          fuelTankCapacityL: 3.6,
          oilTankCapacityL: 1.6,
          airFilter: 'Oil Bath',
          engineDimensionsMm: '390 x 330 x 330',
          transmission: 'Gearbox',
          clutchType: 'Multidisc friction',
          gears: '4 + 2',
          workingWidthMm: '600 - 800 - 1000',
          handleType: 'Height regulation - Reversible',
          blades: 32,
          workingDepthMm: 320,
          security: 'Automatic stop',
          includedAccessories: [
            'Wheels 400 x 8mm',
            'Fuel purge lever',
            'Water pump',
            'PTO for extra accessories',
            'Fumigation pump',
            'Grass cutter',
            'Ditching machine',
          ],
          dimensionsMm: '1600 x 1000 x 1050',
          netWeightKg: 91,
          grossWeightKg: 101,
          containerCapacity: {
            twentyFoot: 48,
            fortyFoot: 96,
            fortyHQ: 144,
          },
          eanCode: '8434691266711',
          manufacturer: 'DUCATI Licensed',
        },
      },
      {
        title: 'Motobomba Aguas Limpias DCW502',
        brand: 'Ducati',
        model: 'DCW502',
        category: 'Motobomba Aguas Limpias',
        specs: {
          displacementCc: 212,
          maxPowerKw: 5.2,
          ratedPowerKw: 4.1,
          ratedPowerHp: 5.6,
          maxRpm: 3600,
          starter: 'Manual',
          ignition: 'Transistorized magneto',
          suctionPortInches: 2,
          dischargePortInches: 2,
          totalLiftM: 38,
          suctionLiftM: 7,
          maxPumpingRateLh: 35000,
          mechanicalSeal:
            'Ceramic seal bellow, Aluminum body pump, Cast Iron Impulsor with keyway',
          suctionDischargeFitting:
            '2"x50mm Aluminum fitting, aluminum fixing nut',
          hoseClamps: 3,
          suctionFilter: '50 mm Polyethylene',
          grilleOnEscape: true,
          lengthMm: 515,
          widthMm: 430,
          heightMm: 445,
          dryWeightKg: 25,
          grossWeightKg: 27,
          fuelTankCapacityL: 4,
          containerCapacity: {
            twentyFoot: 360,
            fortyFoot: 1300,
            fortyHQ: 1500,
          },
          eanCode: '8434691037090',
          manufacturer: 'DUCATI Licensed',
        },
      },
      {
        title: 'Motobomba Aguas Limpias DCW802',
        brand: 'Ducati',
        model: 'DCW802',
        category: 'Motobomba Aguas Limpias',
        specs: {
          displacementCc: 212,
          maxPowerKw: 5.2,
          ratedPowerKw: 4.1,
          ratedPowerHp: 5.6,
          maxRpm: 3600,
          starter: 'Manual',
          ignition: 'Transistorized magneto',
          suctionPortInches: 3,
          dischargePortInches: 3,
          totalLiftM: 32,
          suctionLiftM: 7,
          maxPumpingRateLh: 57000,
          mechanicalSeal:
            'Ceramic seal bellow, Aluminum body pump, Cast Iron Impulsor with keyway',
          suctionDischargeFitting:
            '3"x75mm aluminum fitting, aluminum fixing nut',
          hoseClamps: 3,
          suctionFilter: '75 mm Polyethylene',
          grilleOnEscape: true,
          lengthMm: 515,
          widthMm: 430,
          heightMm: 445,
          dryWeightKg: 28,
          grossWeightKg: 30,
          fuelTankCapacityL: 4,
          containerCapacity: {
            twentyFoot: 360,
            fortyFoot: 1300,
            fortyHQ: 1500,
          },
          eanCode: '8434691037106',
          manufacturer: 'DUCATI Licensed',
        },
      },
      {
        title: 'Motor 4T OHV Monocilíndrico DPE 390Q',
        brand: 'Ducati',
        model: 'DPE 390Q',
        category: 'Motor 4T OHV Monocilíndrico',
        specs: {
          displacementCc: 389,
          maxPowerHp: 13,
          ratedPowerKw: 10.4,
          ratedPowerHp: 14,
          takeStrength: 'Cylindrical with key 25,4 x 72,2 mm',
          boreStroke: '88 x 64 mm',
          compressionRatio: 8.0,
          netTorqueNm: 25,
          governorSystem: 'Centrifugal mechanical',
          airFilter: 'Semi-Dry',
          oilTankCapacityL: 1.1,
          fuelTankCapacityL: 6.5,
          fuelConsumption: '≤ 374 g/kw x h',
          starter: 'Manual / Recoil',
          lengthMm: 530,
          widthMm: 430,
          heightMm: 510,
          netWeightKg: 28,
          containerCapacity: {
            twentyFoot: 220,
            fortyFoot: 460,
            fortyHQ: 575,
          },
          eanCode: '8434691309852',
          manufacturer: 'DUCATI Licensed',
          optionalFeatures: ['Wet air filter in oil', 'Silent aluminized'],
        },
      },
      {
        title: 'Motor 4T OHV Monocilíndrico DPE 210Q',
        brand: 'Ducati',
        model: 'DPE 210Q',
        category: 'Motor 4T OHV Monocilíndrico',
        specs: {
          displacementCc: 212,
          maxPowerHp: 7,
          ratedPowerKw: 5.33,
          ratedPowerHp: 7.0,
          takeStrength: 'Cylindrical with key 19,05 x 58,5 mm',
          boreStroke: '70 x 55 mm',
          compressionRatio: 8.5,
          netTorqueNm: 12,
          governorSystem: 'Centrifugal mechanical',
          airFilter: 'Semi-Dry',
          oilTankCapacityL: 0.6,
          fuelTankCapacityL: 3.6,
          fuelConsumption: '≤ 395 g/kw x h',
          starter: 'Manual / Recoil',
          lengthMm: 400,
          widthMm: 375,
          heightMm: 380,
          netWeightKg: 16,
          containerCapacity: {
            twentyFoot: 490,
            fortyFoot: 1020,
            fortyHQ: 1020,
          },
          eanCode: '8434691309838',
          manufacturer: 'DUCATI Licensed',
          optionalFeatures: ['Wet air filter in oil'],
        },
      },
      {
        title: 'Pulverizador Mochila Líquidos DSP 2500',
        brand: 'Ducati',
        model: 'DSP 2500',
        category: 'Pulverizador Mochila Líquidos',
        specs: [
          {
            displacementCc: 25.4,
            maxPowerKw: 0.7,
            maxPowerHp: 1,
            speedRpm: 7500,
            fuelTankCapacityL: 0.65,
            liquidTankCapacityL: 20,
            liquidFlowPerHoseLMin: '6 - 7',
            maxPressurePsi: 500,
            workingPressureBar: 25,
            netWeightKg: 9,
            grossWeightKg: 11,
            dimensionsMm: '425 x 375 x 550',
            containerCapacity: {
              twentyFoot: 325,
              fortyFoot: 740,
              fortyHQ: 780,
            },
            eanCode: '8434691036055',
            features: ['Pressure control knob', 'Reinforced strap harness'],
          },
          {
            displacementCc: 25.4,
            maxPowerKw: 0.7,
            maxPowerHp: 1,
            speedRpm: 7500,
            fuelTankCapacityL: 0.65,
            liquidTankCapacityL: 15,
            liquidFlowPerHoseLMin: '6 - 7',
            maxPressurePsi: 500,
            workingPressureBar: 25,
            netWeightKg: 9,
            grossWeightKg: 11,
            dimensionsMm: '425 x 350 x 535',
            containerCapacity: {
              twentyFoot: 350,
              fortyFoot: 800,
              fortyHQ: 850,
            },
            eanCode: '8434691036109',
            features: ['Pressure control knob', 'Reinforced strap harness'],
          },
          {
            displacementCc: 25.4,
            maxPowerKw: 0.75,
            maxPowerHp: 1,
            speedRpm: 7000,
            fuelTankCapacityL: 0.75,
            liquidTankCapacityL: 25,
            liquidFlowPerHoseLMin: '4 - 5',
            maxPressurePsi: 500,
            workingPressureBar: 25,
            netWeightKg: 9.5,
            grossWeightKg: 11.8,
            dimensionsMm: '490 x 340 x 645',
            containerCapacity: {
              twentyFoot: 220,
              fortyFoot: 470,
              fortyHQ: 560,
            },
            eanCode: '8434691305182',
            features: [
              'Pressure control knob',
              'Reinforced strap harness',
              'Two Triple Nozzle Lances',
            ],
          },
        ],
        manufacturer: 'DUCATI Licensed',
      },
      {
        title: 'Planta de Emergencia EZ6500CXS',
        brand: 'Ducati',
        model: 'EZ6500CXS',
        category: 'Planta de Emergencia',
        specs: [
          {
            maxPowerKVA: 6.5,
            ratedPowerKVA: 5.5,
            voltageV: 220,
            engineModel: 'GX390',
            fuelType: 'Gasolina de 90',
            fuelTankCapacityL: 15.5,
            oilTankCapacityL: 1.1,
            continuousOperationHours: 5.4,
            ignitionSystem: 'Magneto Transistorizado',
            coolingSystem: 'Forzada de aire',
            cylinderCount: 1,
            displacementCc: 389,
            dimensionsMm: '685 x 535 x 540',
            dryWeightKg: 80,
            accessoriesIncluded: ['Aceite', 'Manual de uso'],
            application: 'Iluminación, Planta de Emergencia',
            startSystem: 'Eléctrico',
          },
        ],
        manufacturer: 'DUCATI Licensed',
      },
      {
        title: 'Motor GP160H QH1',
        brand: 'Honda',
        model: 'GP160H QH1',
        category: 'Motor Multipropósito',
        specs: [
          {
            maxPowerHp: 5.5,
            ratedPowerHp: 4.8,
            rpm: 3600,
            compressionRatio: '8.5:1',
            fuelTankCapacityL: 3.1,
            oilTankCapacityL: 0.58,
            continuousOperationHours: 7,
            ignitionSystem: 'Magneto Transistorizado',
            coolingSystem: 'Aire Forzado',
            shaftType: 'Chavetero',
            sparkPlugGapMm: '0.7 - 0.8',
            cylinderCount: 1,
            displacementCc: 163,
            dimensionsMm: '314 x 363 x 335',
            dryWeightKg: 14.9,
            use: 'Agricultura, Minería Artesanal, Ganadería, Jardinería, Construcción',
            application:
              'Motobomba, Despulpadora de Café, Molino de Cereales, Lavador de Minerales, etc.',
            accessoriesIncluded: [
              'Aceite',
              'Manual de Usuario',
              'Certificado de Garantía',
              'Kit de Herramientas',
            ],
            warranty: '1 Año',
          },
        ],
        manufacturer: 'Honda',
      },
      {
        title: 'Motor GX430',
        brand: 'Honda',
        model: 'GX430 QX',
        category: 'Motor Multifuncional',
        specs: [
          {
            maxPowerHp: 14,
            ratedPowerKw: 9.6,
            ratedPowerHp: 13.05,
            rpm: 3000,
            compressionRatio: '9.0',
            coolingSystem: 'Aire Forzado',
            ignitionSystem: 'Magneto Transistorizado',
            carburetor: 'Válvula de mariposa tipo horizontal',
            airFilter: 'Tipo dual',
            lubricationSystem: 'Salpicadura forzada',
            oilTankCapacityL: 1.1,
            starterSystem: 'Cuerda Retráctil',
            recommendedFuel: 'Gasolina sin plomo superior a 86 oct',
            fuelTankCapacityL: 6.1,
            displacementCc: 425,
            boreAndStroke: '88.0 x 70.0 mm (3.46 x 2.75 in)',
            dimensionsMm: '387 x 469 x 453',
            dryWeightKg: 32,
            applications: [
              'Mezcladora',
              'Generadores',
              'Motobombas',
              'Cortadora de concreto',
              'Hidrolavadora de presión',
              'Compactadora',
            ],
          },
        ],
        manufacturer: 'Honda',
      },
      {
        title: 'Bomba Tragasólidos WT30XK4',
        brand: 'Honda',
        model: 'WT30XK4',
        category: 'Bomba Tragasólidos',
        specs: [
          {
            pumpType: 'Tragasólidos',
            suctionAndDischargeDiameterInches: 3,
            maxTotalLiftM: 27,
            maxSuctionLiftM: 8,
            maxFlowLMin: 1200,
            widthMm: 660,
            dryWeightKg: 61,
            lengthMm: 495,
            heightMm: 515,
            engineModel: 'GX270T2',
            engineType: 'Monocilíndrico',
            valveSystem: '4 tiempos OHV',
            maxPowerHp: 9,
            maxPowerRpm: 3600,
            warrantyYears: 2,
            performanceCurves: [200, 400, 800, 600, 1000, 1200, 1400], // Puede representarse en una gráfica si se desea
            applications: [
              'Bomba de aguas sucias',
              'Industria de construcción',
              'Agricultura',
            ],
          },
        ],
        manufacturer: 'Honda',
      },
      {
        title: 'Bomba Autocebante WL20XH',
        brand: 'Honda',
        model: 'WL20XH',
        category: 'Bomba Autocebante',
        specs: [
          {
            pumpType: 'Autocebante',
            suctionAndDischargeDiameterInches: 2,
            maxTotalLiftM: 32,
            maxSuctionLiftM: 7.5,
            maxFlowLMin: 670,
            widthMm: 385,
            dryWeightKg: 24,
            lengthMm: 490,
            heightMm: 410,
            engineModel: 'GP160H',
            engineType: 'Monocilíndrico',
            valveSystem: '4-Tiempos, OHV',
            maxPowerHp: 5.5,
            maxPowerRpm: 3600,
            warrantyYears: 1,
            performanceCurves: [0, 100, 200, 300, 400, 500, 600, 700],
            accessoriesIncluded: [
              'Kit de empaques',
              '3 abrazaderas',
              '2 bridas de ajuste',
              '2 acoples de manguera',
              '2 empaques de acople de manguera',
              '1 canastilla',
              '1 sacabujías con palanca',
            ],
            applications: [
              'Bomba de aguas limpias',
              'Industria de construcción',
              'Agricultura',
            ],
          },
        ],
        manufacturer: 'Honda',
      },
      {
        title: 'Bomba Autocebante WL20XH',
        brand: 'Honda',
        model: 'WL20XH',
        category: 'Bomba Autocebante',
        specs: [
          {
            pumpType: 'Autocebante',
            suctionAndDischargeDiameterInches: 2,
            maxTotalLiftM: 32,
            maxSuctionLiftM: 7.5,
            maxFlowLMin: 670,
            widthMm: 385,
            dryWeightKg: 24,
            lengthMm: 490,
            heightMm: 410,
            engineModel: 'GP160H',
            engineType: 'Monocilíndrico',
            valveSystem: '4-Tiempos, OHV',
            maxPowerHp: 5.5,
            maxPowerRpm: 3600,
            warrantyYears: 1,
            performanceCurves: [0, 100, 200, 300, 400, 500, 600, 700],
            accessoriesIncluded: [
              'Kit de empaques',
              '3 abrazaderas',
              '2 bridas de ajuste',
              '2 acoples de manguera',
              '2 empaques de acople de manguera',
              '1 canastilla',
              '1 sacabujías con palanca',
            ],
            applications: [
              'Bomba de aguas limpias',
              'Industria de construcción',
              'Agricultura',
            ],
          },
        ],
        manufacturer: 'Honda',
      },
      {
        title: 'Bomba Autocebante WL20XH',
        brand: 'Honda',
        model: 'WL20XH',
        category: 'Bomba Autocebante',
        specs: [
          {
            pumpType: 'Autocebante',
            suctionAndDischargeDiameterInches: 2,
            maxTotalLiftM: 32,
            maxSuctionLiftM: 7.5,
            maxFlowLMin: 670,
            widthMm: 385,
            dryWeightKg: 24,
            lengthMm: 490,
            heightMm: 410,
            engineModel: 'GP160H',
            engineType: 'Monocilíndrico',
            valveSystem: '4-Tiempos, OHV',
            maxPowerHp: 5.5,
            maxPowerRpm: 3600,
            warrantyYears: 1,
            performanceCurves: [0, 100, 200, 300, 400, 500, 600, 700],
            accessoriesIncluded: [
              'Kit de empaques',
              '3 abrazaderas',
              '2 bridas de ajuste',
              '2 acoples de manguera',
              '2 empaques de acople de manguera',
              '1 canastilla',
              '1 sacabujías con palanca',
            ],
            applications: [
              'Bomba de aguas limpias',
              'Industria de construcción',
              'Agricultura',
            ],
          },
        ],
        manufacturer: 'Honda',
      },
      {
        title: 'Bomba Autocebante WB30XH2',
        brand: 'Honda',
        model: 'WB30XH2',
        category: 'Bomba Autocebante',
        specs: [
          {
            pumpType: 'Autocebante',
            suctionAndDischargeDiameterInches: 3,
            maxTotalLiftM: 28,
            maxSuctionLiftM: 8,
            maxFlowLMin: 1100,
            widthMm: 385,
            dryWeightKg: 27,
            lengthMm: 510,
            heightMm: 435,
            engineModel: 'GX160H1',
            engineType: 'Monocilíndrico',
            valveSystem: '4-Tiempos, OHV',
            maxPowerHp: 5.5,
            maxPowerRpm: 3600,
            warrantyYears: 2,
            performanceCurves: [200, 400, 600, 800, 1000],
            accessoriesIncluded: [
              '3 abrazaderas',
              '2 bridas de ajuste',
              '2 acoples de manguera',
              '2 empaques de acople de manguera',
              '1 canastilla',
              '1 sacabujías con palanca',
            ],
            applications: [
              'Bomba de aguas limpias',
              'Construcción',
              'Agricultura',
            ],
          },
        ],
        manufacturer: 'Honda',
      },
      {
        title: 'Bomba Tragasólidos WT40XK3',
        brand: 'Honda',
        model: 'WT40XK3',
        category: 'Bomba Tragasólidos',
        specs: [
          {
            pumpType: 'Tragasólidos',
            suctionAndDischargeDiameterInches: 4,
            maxTotalLiftM: 25,
            maxSuctionLiftM: 8,
            maxFlowLMin: 1600,
            widthMm: 535,
            dryWeightKg: 78,
            lengthMm: 735,
            heightMm: 565,
            engineModel: 'GX390T2',
            engineType: 'Monocilíndrico',
            valveSystem: '4-Tiempos, OHV',
            maxPowerHp: 13,
            maxPowerRpm: 3600,
            warrantyYears: 2,
            performanceCurves: [200, 400, 600, 800, 1000],
            accessoriesIncluded: [
              '3 abrazaderas',
              '2 bridas de ajuste',
              '2 acoples de manguera',
              '2 empaques de acople de manguera',
              '1 canastilla',
            ],
            applications: ['Tragado de sólidos', 'Construcción', 'Agricultura'],
          },
        ],
        manufacturer: 'Honda',
      },
      {
        title: 'Generador EG1000N',
        brand: 'Honda',
        model: 'EG1000N',
        category: 'Generador',
        specs: [
          {
            maxOutputVA: 1000,
            nominalOutputVA: 900,
            frequencyHz: 60,
            outputVoltageV: 220,
            engineModel: 'GX80D',
            engineType: '4 tiempos - OHV',
            valveSystem: 'Monocilíndrico',
            displacementCm3: 79.7,
            fuelTankCapacityL: 3.6,
            continuousOperationHours: 5.5,
            startSystem: 'Arranque retractil o de retroceso',
            noiseLevelDb: 'Bajo carga nominal a 7m',
            fuelType: 'Gasolina de 90',
            warrantyYears: 2,
            phase: 'Monofásico',
            voltageRegulator: 'No',
            ecoThrottleRegulator: 'No',
            batteryCharger: 'No',
            acCircuitBreaker: 'No',
            voltmeter: 'No',
            fuelGauge: 'No',
            oilAlert: 'No',
            electricStart: 'No',
            overloadAlarm: 'No',
            engineOilCapacityL: 0.36,
            recommendedOil: 'SAE 10W-30 API',
            accessoriesIncluded: [
              '1 enchufe 15A/250V',
              '1 sacabujías con palanca',
            ],
            applications: [
              'Iluminación',
              'Uso doméstico',
              'Agricultura',
              'Recreación',
            ],
            dimensions: {
              lengthMm: 376,
              widthMm: 301,
              heightMm: 430,
            },
            dryWeightKg: 22.5,
          },
        ],
        manufacturer: 'Honda',
      },
      {
        title: 'Generador EG5000CX',
        brand: 'Honda',
        model: 'EG5000CX',
        category: 'Generador',
        specs: [
          {
            maxOutputVA: 5000,
            nominalOutputVA: 4500,
            frequencyHz: 60,
            outputVoltageV: '120/240',
            dcNominalCurrentA: 8.3,
            engineModel: 'GX340H1',
            engineType: '4 tiempos - OHC',
            valveSystem: 'Monocilíndrico',
            displacementCm3: 337,
            fuelTankCapacityL: 24,
            continuousOperationHours: 8.5,
            startSystem: 'Arranque retractil o de retroceso',
            noiseLevelDb: 101,
            fuelType: 'Gasolina de 90',
            warrantyYears: 2,
            phase: 'Monofásico',
            voltageRegulator: 'Digital',
            ecoThrottleRegulator: 'No',
            batteryCharger: 'No',
            acCircuitBreaker: 'Sí',
            voltmeter: 'Sí',
            fuelGauge: 'No',
            oilAlert: 'No',
            electricStart: 'No',
            overloadAlarm: 'No',
            engineOilCapacityL: 1.1,
            recommendedOil: 'SAE 10W-30 API',
            accessoriesIncluded: [
              '2 enchufes 15A/125V',
              '1 enchufe 30A-125/250V',
              '1 enchufe 30A/125V',
              '1 sacabujías con palanca',
            ],
            applications: [
              'Iluminación',
              'Herramientas Eléctricas',
              'Uso doméstico',
              'Minería',
              'Construcción',
              'Agricultura',
            ],
            dimensions: {
              lengthMm: 681,
              widthMm: 530,
              heightMm: 571,
            },
            dryWeightKg: 82.5,
          },
        ],
        manufacturer: 'Honda',
      },
      {
        title: 'Generador EG6500CXS-S1H',
        brand: 'Honda',
        model: 'EG6500CXS-S1H',
        category: 'Generador',
        specs: [
          {
            maxOutputVA: 6500,
            nominalOutputVA: 5500,
            frequencyHz: 60,
            outputVoltageV: '220',
            dcNominalCurrentA: 8.3,
            engineModel: 'GX390H1',
            engineType: '4 tiempos - OHC',
            valveSystem: 'Monocilíndrico',
            displacementCm3: 389,
            fuelTankCapacityL: 24,
            continuousOperationHours: 7,
            startSystem:
              'Arranque retractil o de retroceso y arranque automatico a batería',
            noiseLevelDb: 102,
            fuelType: 'Gasolina de 90',
            warrantyYears: 2,
            phase: 'Monofásico',
            voltageRegulator: 'Digital',
            ecoThrottleRegulator: 'No',
            batteryCharger: 'Sí',
            acCircuitBreaker: 'Sí',
            voltmeter: 'Sí',
            fuelGauge: 'Sí',
            oilAlert: 'Sí',
            electricStart: 'Sí',
            overloadAlarm: 'No',
            engineOilCapacityL: 1.1,
            recommendedOil: 'SAE 10W-30 API',
            accessoriesIncluded: [
              '2 enchufes 20A/250V',
              '1 sacabujías con palanca',
            ],
            applications: [
              'Iluminación',
              'Herramientas Eléctricas',
              'Uso doméstico',
              'Minería',
              'Construcción',
              'Agricultura',
            ],
            dimensions: {
              lengthMm: 844,
              widthMm: 530,
              heightMm: 571,
            },
            dryWeightKg: 87,
          },
        ],
        manufacturer: 'Honda',
      },
      {
        title: 'Generador EM10000K1',
        brand: 'Honda',
        model: 'EM10000K1',
        category: 'Generador',
        specs: [
          {
            maxOutputVA: 10000,
            nominalOutputVA: 9000,
            frequencyHz: 60,
            outputVoltageV: '120 / 240',
            dcNominalCurrentA: null, // No disponible
            engineModel: 'GX630H',
            engineType: '4 tiempos - OHV',
            valveSystem: 'Bicilíndrico - V TWIN',
            displacementCm3: 688,
            fuelTankCapacityL: 31,
            continuousOperationHours: 5.3,
            startSystem: 'Arranque automático a batería',
            noiseLevelDb: 103.4,
            fuelType: 'Gasolina de 90',
            warrantyYears: 2,
            phase: 'Monofásico',
            voltageRegulator: 'Digital',
            ecoThrottleRegulator: 'No',
            batteryCharger: 'No',
            acCircuitBreaker: 'Sí',
            voltmeter: 'No',
            fuelGauge: 'Sí',
            oilAlert: 'No',
            electricStart: 'Sí',
            overloadAlarm: 'No',
            engineOilCapacityL: 1.5,
            recommendedOil: 'SAE 10W-30 API',
            accessoriesIncluded: [
              '4 enchufes 15A / 125V',
              '1 enchufe 50A/125-250V',
              '1 enchufe 30A/125-250V',
              '1 enchufe 30A/125V',
              '1 sacabujías con palanca',
              '1 embudo para aceite',
              '1 batería',
            ],
            applications: [
              'Iluminación',
              'Herramientas Eléctricas',
              'Uso doméstico',
              'Minería',
              'Construcción',
              'Agricultura',
            ],
            dimensions: {
              lengthMm: 973,
              widthMm: 552,
              heightMm: 695,
            },
            dryWeightKg: 162.3,
          },
        ],
        manufacturer: 'Honda',
      },
    ],
  });

  console.log('🌱 Seeds cargados correctamente con todos los productos.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
