name: Run tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v3
      - run: echo DATABASE_URL
      - run: npm i
      - run: echo DATABASE_URL=${{ secrets.DATABASE_URL }} > .env
      - run: npm run test
