name: Run tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: development
    container:
      image: node:20
    services:
      postgres:
        image: postgres:15  # PostgreSQL container image
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432  # Expose the PostgreSQL port
        options: >-
          --health-cmd="pg_isready -U postgres -d testdb"  # Wait for PostgreSQL to be ready and ensure the testdb is available
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3
      - run: npm install -g pnpm@latest-10
      - run: echo "DATABASE_URL=postgresql://postgres:password@postgres:5432/testdb" >> .env  # Use the service name 'postgres' for the DB URL
      - run: pnpm install  # Install dependencies using pnpm
      - run: rm -rf prisma/migrations  # Clean migrations if necessary
      - run: pnpm run prisma:migrate  # Run migrations
      - run: pnpm run prisma:seed  # Seed the database
      - run: pnpm run test  # Run tests
