name: Run tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production  # Specify the environment where secrets are stored
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
      - run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}"  # Debugging step
      - run: npm i
      - run: npm run test
