name: Run tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: development  # Specify the environment where secrets are stored
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
      - run: echo "DATABASE_URL=${{ vars.DATABASE_URL }}" >> .env  # Save secret to .env file
      - run: npm ci
      - run: npm run prisma:migrate
      - run: npm run prisma:seed
      - run: npm run test
